package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA



/**
 * CaraproductoId generated by hbm2java
 */
public class CaraproductoId  implements java.io.Serializable {

     private int idcara;
     private int idproducto;

    public int getIdcara() {
        return this.idcara;
    }
    
    public void setIdcara(int idcara) {
        this.idcara = idcara;
    }
    public int getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(int idproducto) {
        this.idproducto = idproducto;
    }

}


