package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Caraproducto generated by hbm2java
 */
public class Caraproducto  implements java.io.Serializable {


     private CaraproductoId id;
     private Producto producto;
     private Cara cara;
     private Date fecharegistro;
     private Set<Despacho> despachos = new HashSet<Despacho>(0);
   
    public CaraproductoId getId() {
        return this.id;
    }
    
    public void setId(CaraproductoId id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Cara getCara() {
        return this.cara;
    }
    
    public void setCara(Cara cara) {
        this.cara = cara;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Set<Despacho> getDespachos() {
        return this.despachos;
    }
    
    public void setDespachos(Set<Despacho> despachos) {
        this.despachos = despachos;
    }




}


