package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA



/**
 * CentroemisortipocomprobanteId generated by hbm2java
 */
public class CentroemisortipocomprobanteId  implements java.io.Serializable {


     private int idtipocomprobante;
     private int idcentroemisor;
   
    public int getIdtipocomprobante() {
        return this.idtipocomprobante;
    }
    
    public void setIdtipocomprobante(int idtipocomprobante) {
        this.idtipocomprobante = idtipocomprobante;
    }
    public int getIdcentroemisor() {
        return this.idcentroemisor;
    }
    
    public void setIdcentroemisor(int idcentroemisor) {
        this.idcentroemisor = idcentroemisor;
    }

}


