package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Centroemisor generated by hbm2java
 */
public class Centroemisor  implements java.io.Serializable {


     private int id;
     private Puntoventa puntoventa;
     private String emisor;
     private Date fecharegistro;
     private Set<Centroemisortipocomprobante> centroemisortipocomprobantes = new HashSet<Centroemisortipocomprobante>(0);
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Puntoventa getPuntoventa() {
        return this.puntoventa;
    }
    
    public void setPuntoventa(Puntoventa puntoventa) {
        this.puntoventa = puntoventa;
    }
    public String getEmisor() {
        return this.emisor;
    }
    
    public void setEmisor(String emisor) {
        this.emisor = emisor;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Set<Centroemisortipocomprobante> getCentroemisortipocomprobantes() {
        return this.centroemisortipocomprobantes;
    }
    
    public void setCentroemisortipocomprobantes(Set<Centroemisortipocomprobante> centroemisortipocomprobantes) {
        this.centroemisortipocomprobantes = centroemisortipocomprobantes;
    }




}


