package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int id;
     private String numerodocumento;
     private String razonsocial;
     private Integer idtipodocumento;
     private Date fecharegistro;
     private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);
     private Set<Tarjeta> tarjetas = new HashSet<Tarjeta>(0);
     private Set<Cuenta> cuentas = new HashSet<Cuenta>(0);

    public Cliente() {
    }

	
    public Cliente(int id) {
        this.id = id;
    }
    public Cliente(int id, String numerodocumento, String razonsocial, Integer idtipodocumento, Date fecharegistro, Set<Transaccion> transaccions, Set<Tarjeta> tarjetas, Set<Cuenta> cuentas) {
       this.id = id;
       this.numerodocumento = numerodocumento;
       this.razonsocial = razonsocial;
       this.idtipodocumento = idtipodocumento;
       this.fecharegistro = fecharegistro;
       this.transaccions = transaccions;
       this.tarjetas = tarjetas;
       this.cuentas = cuentas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNumerodocumento() {
        return this.numerodocumento;
    }
    
    public void setNumerodocumento(String numerodocumento) {
        this.numerodocumento = numerodocumento;
    }
    public String getRazonsocial() {
        return this.razonsocial;
    }
    
    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial;
    }
    public Integer getIdtipodocumento() {
        return this.idtipodocumento;
    }
    
    public void setIdtipodocumento(Integer idtipodocumento) {
        this.idtipodocumento = idtipodocumento;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Set<Transaccion> getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set<Transaccion> transaccions) {
        this.transaccions = transaccions;
    }
    public Set<Tarjeta> getTarjetas() {
        return this.tarjetas;
    }
    
    public void setTarjetas(Set<Tarjeta> tarjetas) {
        this.tarjetas = tarjetas;
    }
    public Set<Cuenta> getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set<Cuenta> cuentas) {
        this.cuentas = cuentas;
    }




}


