package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Deposito generated by hbm2java
 */
public class Deposito  implements java.io.Serializable {


     private int id;
     private Turnopuntoventacaja turnopuntoventacaja;
     private Double montototal;
     private Date fecharegistro;
     private String idtipopago;
     private String turno;
     private String cerrado;

    public Deposito() {
    }

    public Deposito(int id, Turnopuntoventacaja turnopuntoventacaja, Double montototal, Date fecharegistro, String idtipopago, String turno, String cerrado) {
        this.id = id;
        this.turnopuntoventacaja = turnopuntoventacaja;
        this.montototal = montototal;
        this.fecharegistro = fecharegistro;
        this.idtipopago = idtipopago;
        this.turno = turno;
        this.cerrado = cerrado;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Turnopuntoventacaja getTurnopuntoventacaja() {
        return turnopuntoventacaja;
    }

    public void setTurnopuntoventacaja(Turnopuntoventacaja turnopuntoventacaja) {
        this.turnopuntoventacaja = turnopuntoventacaja;
    }

    public Double getMontototal() {
        return montototal;
    }

    public void setMontototal(Double montototal) {
        this.montototal = montototal;
    }

    public Date getFecharegistro() {
        return fecharegistro;
    }

    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }

    public String getIdtipopago() {
        return idtipopago;
    }

    public void setIdtipopago(String idtipopago) {
        this.idtipopago = idtipopago;
    }

    public String getTurno() {
        return turno;
    }

    public void setTurno(String turno) {
        this.turno = turno;
    }

    public String getCerrado() {
        return cerrado;
    }

    public void setCerrado(String cerrado) {
        this.cerrado = cerrado;
    }

   

    
}


