package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA



/**
 * DistritoId generated by hbm2java
 */
public class DistritoId  implements java.io.Serializable {


     private String id;
     private String idprovincia;
     private String iddepartamento;

    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getIdprovincia() {
        return this.idprovincia;
    }
    
    public void setIdprovincia(String idprovincia) {
        this.idprovincia = idprovincia;
    }
    public String getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(String iddepartamento) {
        this.iddepartamento = iddepartamento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DistritoId) ) return false;
		 DistritoId castOther = ( DistritoId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getIdprovincia()==castOther.getIdprovincia()) || ( this.getIdprovincia()!=null && castOther.getIdprovincia()!=null && this.getIdprovincia().equals(castOther.getIdprovincia()) ) )
 && ( (this.getIddepartamento()==castOther.getIddepartamento()) || ( this.getIddepartamento()!=null && castOther.getIddepartamento()!=null && this.getIddepartamento().equals(castOther.getIddepartamento()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getIdprovincia() == null ? 0 : this.getIdprovincia().hashCode() );
         result = 37 * result + ( getIddepartamento() == null ? 0 : this.getIddepartamento().hashCode() );
         return result;
   }   


}


