package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA



/**
 * ImpresorapuntoventaId generated by hbm2java
 */
public class ImpresorapuntoventaId  implements java.io.Serializable {


     private int idpuntoventa;
     private int idimpresora;

    public ImpresorapuntoventaId() {
    }

    public ImpresorapuntoventaId(int idpuntoventa, int idimpresora) {
       this.idpuntoventa = idpuntoventa;
       this.idimpresora = idimpresora;
    }
   
    public int getIdpuntoventa() {
        return this.idpuntoventa;
    }
    
    public void setIdpuntoventa(int idpuntoventa) {
        this.idpuntoventa = idpuntoventa;
    }
    public int getIdimpresora() {
        return this.idimpresora;
    }
    
    public void setIdimpresora(int idimpresora) {
        this.idimpresora = idimpresora;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ImpresorapuntoventaId) ) return false;
		 ImpresorapuntoventaId castOther = ( ImpresorapuntoventaId ) other; 
         
		 return (this.getIdpuntoventa()==castOther.getIdpuntoventa())
 && (this.getIdimpresora()==castOther.getIdimpresora());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdpuntoventa();
         result = 37 * result + this.getIdimpresora();
         return result;
   }   


}


