package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * InterfaceConfig generated by hbm2java
 */
public class InterfaceConfig  implements java.io.Serializable {


     private int codigo;
     private Integer cambioturno;
     private Integer cierredia;
     private Date fechaTotalizadoresElectronicos;
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public Integer getCambioturno() {
        return this.cambioturno;
    }
    
    public void setCambioturno(Integer cambioturno) {
        this.cambioturno = cambioturno;
    }
    public Integer getCierredia() {
        return this.cierredia;
    }
    
    public void setCierredia(Integer cierredia) {
        this.cierredia = cierredia;
    }
    public Date getFechaTotalizadoresElectronicos() {
        return this.fechaTotalizadoresElectronicos;
    }
    
    public void setFechaTotalizadoresElectronicos(Date fechaTotalizadoresElectronicos) {
        this.fechaTotalizadoresElectronicos = fechaTotalizadoresElectronicos;
    }




}


