package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Listavalor generated by hbm2java
 */
public class Listavalor  implements java.io.Serializable {


     private int id;
     private Listavalor listavalor;
     private Lista lista;
     private String nombre;
     private Date fecharegistro;
     private Set<Listavalor> listavalors = new HashSet<Listavalor>(0);

    public Listavalor() {
    }

	
    public Listavalor(int id, Lista lista) {
        this.id = id;
        this.lista = lista;
    }
    
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Listavalor getListavalor() {
        return this.listavalor;
    }
    
    public void setListavalor(Listavalor listavalor) {
        this.listavalor = listavalor;
    }
    public Lista getLista() {
        return this.lista;
    }
    
    public void setLista(Lista lista) {
        this.lista = lista;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Set<Listavalor> getListavalors() {
        return this.listavalors;
    }
    
    public void setListavalors(Set<Listavalor> listavalors) {
        this.listavalors = listavalors;
    }




}


