package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA



/**
 * Numcomprobante generated by hbm2java
 */
public class Numcomprobante  implements java.io.Serializable {


     private int codigo;
     private String tipo;
     private Integer numero;

    public Numcomprobante() {
    }

	
    public Numcomprobante(int codigo) {
        this.codigo = codigo;
    }
    public Numcomprobante(int codigo, String tipo, Integer numero) {
       this.codigo = codigo;
       this.tipo = tipo;
       this.numero = numero;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }




}


