package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA



/**
 * PuntoacumuladoId generated by hbm2java
 */
public class PuntoacumuladoId  implements java.io.Serializable {


     private int idtransaccion;
     private int idtarjeta;

    public PuntoacumuladoId() {
    }

    public int getIdtransaccion() {
        return this.idtransaccion;
    }
    
    public void setIdtransaccion(int idtransaccion) {
        this.idtransaccion = idtransaccion;
    }
    public int getIdtarjeta() {
        return this.idtarjeta;
    }
    
    public void setIdtarjeta(int idtarjeta) {
        this.idtarjeta = idtarjeta;
    }
}


