package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Subcuenta generated by hbm2java
 */
public class Subcuenta  implements java.io.Serializable {


     private int id;
     private Cuenta cuenta;
     private Producto producto;
     private Tarjeta tarjeta;
     private String descriocion;
     private Integer idtipomoneda;
     private Integer saldo;
     private Integer limitecredito;
     private Date fecharegistro;

    public Subcuenta() {
    }

	
    public Subcuenta(int id, Cuenta cuenta, Producto producto, Tarjeta tarjeta) {
        this.id = id;
        this.cuenta = cuenta;
        this.producto = producto;
        this.tarjeta = tarjeta;
    }
    public Subcuenta(int id, Cuenta cuenta, Producto producto, Tarjeta tarjeta, String descriocion, Integer idtipomoneda, Integer saldo, Integer limitecredito, Date fecharegistro) {
       this.id = id;
       this.cuenta = cuenta;
       this.producto = producto;
       this.tarjeta = tarjeta;
       this.descriocion = descriocion;
       this.idtipomoneda = idtipomoneda;
       this.saldo = saldo;
       this.limitecredito = limitecredito;
       this.fecharegistro = fecharegistro;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }
    public String getDescriocion() {
        return this.descriocion;
    }
    
    public void setDescriocion(String descriocion) {
        this.descriocion = descriocion;
    }
    public Integer getIdtipomoneda() {
        return this.idtipomoneda;
    }
    
    public void setIdtipomoneda(Integer idtipomoneda) {
        this.idtipomoneda = idtipomoneda;
    }
    public Integer getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Integer saldo) {
        this.saldo = saldo;
    }
    public Integer getLimitecredito() {
        return this.limitecredito;
    }
    
    public void setLimitecredito(Integer limitecredito) {
        this.limitecredito = limitecredito;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }




}


