package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tarjeta generated by hbm2java
 */
public class Tarjeta  implements java.io.Serializable {


     private int id;
     private Cliente cliente;
     private String nombrechofer;
     private String numeroplaca;
     private Date fechacaducidad;
     private Date fecharegistro;
     private Set<Subcuenta> subcuentas = new HashSet<Subcuenta>(0);
     private Set<Puntoacumulado> puntoacumulados = new HashSet<Puntoacumulado>(0);

    public Tarjeta() {
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getNombrechofer() {
        return this.nombrechofer;
    }
    
    public void setNombrechofer(String nombrechofer) {
        this.nombrechofer = nombrechofer;
    }
    public String getNumeroplaca() {
        return this.numeroplaca;
    }
    
    public void setNumeroplaca(String numeroplaca) {
        this.numeroplaca = numeroplaca;
    }
    public Date getFechacaducidad() {
        return this.fechacaducidad;
    }
    
    public void setFechacaducidad(Date fechacaducidad) {
        this.fechacaducidad = fechacaducidad;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Set<Subcuenta> getSubcuentas() {
        return this.subcuentas;
    }
    
    public void setSubcuentas(Set<Subcuenta> subcuentas) {
        this.subcuentas = subcuentas;
    }
    public Set<Puntoacumulado> getPuntoacumulados() {
        return this.puntoacumulados;
    }
    
    public void setPuntoacumulados(Set<Puntoacumulado> puntoacumulados) {
        this.puntoacumulados = puntoacumulados;
    }




}


