package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA



/**
 * UsuarioperfilId generated by hbm2java
 */
public class UsuarioperfilId  implements java.io.Serializable {


     private int idusuario;
     private int idperfil;

    public UsuarioperfilId() {
    }

    public int getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(int idusuario) {
        this.idusuario = idusuario;
    }
    public int getIdperfil() {
        return this.idperfil;
    }
    
    public void setIdperfil(int idperfil) {
        this.idperfil = idperfil;
    }

}


