package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Vale generated by hbm2java
 */
public class Vale  implements java.io.Serializable {


     private int id;
     private String cliente;
     private String numero;
     private String producto;
     private Double monto;
     private String chofer;
     private String placa;
     private Date fecha;
     private Integer estado;
     private Date fechadespacho;
     private String horadespacho;

    public Vale() {
    }

	
    public Vale(int id) {
        this.id = id;
    }
    
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getProducto() {
        return this.producto;
    }
    
    public void setProducto(String producto) {
        this.producto = producto;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public String getChofer() {
        return this.chofer;
    }
    
    public void setChofer(String chofer) {
        this.chofer = chofer;
    }
    public String getPlaca() {
        return this.placa;
    }
    
    public void setPlaca(String placa) {
        this.placa = placa;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Date getFechadespacho() {
        return this.fechadespacho;
    }
    
    public void setFechadespacho(Date fechadespacho) {
        this.fechadespacho = fechadespacho;
    }
    public String getHoradespacho() {
        return this.horadespacho;
    }
    
    public void setHoradespacho(String horadespacho) {
        this.horadespacho = horadespacho;
    }




}


