package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA



/**
 * CaraproductoId generated by hbm2java
 */
public class CaraproductoId  implements java.io.Serializable {


     private int idCara;
     private int idProducto;

    public CaraproductoId() {
    }

    public CaraproductoId(int idCara, int idProducto) {
       this.idCara = idCara;
       this.idProducto = idProducto;
    }
   
    public int getIdCara() {
        return this.idCara;
    }
    
    public void setIdCara(int idCara) {
        this.idCara = idCara;
    }
    public int getIdProducto() {
        return this.idProducto;
    }
    
    public void setIdProducto(int idProducto) {
        this.idProducto = idProducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CaraproductoId) ) return false;
		 CaraproductoId castOther = ( CaraproductoId ) other; 
         
		 return (this.getIdCara()==castOther.getIdCara())
 && (this.getIdProducto()==castOther.getIdProducto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdCara();
         result = 37 * result + this.getIdProducto();
         return result;
   }   


}


