package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Centroemisortipocomprobante generated by hbm2java
 */
public class Centroemisortipocomprobante  implements java.io.Serializable {


     private CentroemisortipocomprobanteId id;
     private Centroemisor centroemisor;
     private Date fechaRegistro;

    public Centroemisortipocomprobante() {
    }

	
    public Centroemisortipocomprobante(CentroemisortipocomprobanteId id, Centroemisor centroemisor) {
        this.id = id;
        this.centroemisor = centroemisor;
    }
    public Centroemisortipocomprobante(CentroemisortipocomprobanteId id, Centroemisor centroemisor, Date fechaRegistro) {
       this.id = id;
       this.centroemisor = centroemisor;
       this.fechaRegistro = fechaRegistro;
    }
   
    public CentroemisortipocomprobanteId getId() {
        return this.id;
    }
    
    public void setId(CentroemisortipocomprobanteId id) {
        this.id = id;
    }
    public Centroemisor getCentroemisor() {
        return this.centroemisor;
    }
    
    public void setCentroemisor(Centroemisor centroemisor) {
        this.centroemisor = centroemisor;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


