package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA



/**
 * CentroemisortipocomprobanteId generated by hbm2java
 */
public class CentroemisortipocomprobanteId  implements java.io.Serializable {


     private int idTipoComprobante;
     private int idCentroEmisor;

    public CentroemisortipocomprobanteId() {
    }

    public CentroemisortipocomprobanteId(int idTipoComprobante, int idCentroEmisor) {
       this.idTipoComprobante = idTipoComprobante;
       this.idCentroEmisor = idCentroEmisor;
    }
   
    public int getIdTipoComprobante() {
        return this.idTipoComprobante;
    }
    
    public void setIdTipoComprobante(int idTipoComprobante) {
        this.idTipoComprobante = idTipoComprobante;
    }
    public int getIdCentroEmisor() {
        return this.idCentroEmisor;
    }
    
    public void setIdCentroEmisor(int idCentroEmisor) {
        this.idCentroEmisor = idCentroEmisor;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CentroemisortipocomprobanteId) ) return false;
		 CentroemisortipocomprobanteId castOther = ( CentroemisortipocomprobanteId ) other; 
         
		 return (this.getIdTipoComprobante()==castOther.getIdTipoComprobante())
 && (this.getIdCentroEmisor()==castOther.getIdCentroEmisor());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTipoComprobante();
         result = 37 * result + this.getIdCentroEmisor();
         return result;
   }   


}


