package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Lista generated by hbm2java
 */
public class Lista  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Date fechaRegistro;
     private Set<Listavalor> listavalors = new HashSet<Listavalor>(0);

    public Lista() {
    }

	
    public Lista(int id) {
        this.id = id;
    }
    public Lista(int id, String nombre, Date fechaRegistro, Set<Listavalor> listavalors) {
       this.id = id;
       this.nombre = nombre;
       this.fechaRegistro = fechaRegistro;
       this.listavalors = listavalors;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<Listavalor> getListavalors() {
        return this.listavalors;
    }
    
    public void setListavalors(Set<Listavalor> listavalors) {
        this.listavalors = listavalors;
    }




}


