package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil  implements java.io.Serializable {


     private int id;
     private String nombre;
     private Date fechaRegistro;
     private Set<Perfilopcion> perfilopcions = new HashSet<Perfilopcion>(0);
     private Set<Usuarioperfil> usuarioperfils = new HashSet<Usuarioperfil>(0);

    public Perfil() {
    }

	
    public Perfil(int id) {
        this.id = id;
    }
    public Perfil(int id, String nombre, Date fechaRegistro, Set<Perfilopcion> perfilopcions, Set<Usuarioperfil> usuarioperfils) {
       this.id = id;
       this.nombre = nombre;
       this.fechaRegistro = fechaRegistro;
       this.perfilopcions = perfilopcions;
       this.usuarioperfils = usuarioperfils;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<Perfilopcion> getPerfilopcions() {
        return this.perfilopcions;
    }
    
    public void setPerfilopcions(Set<Perfilopcion> perfilopcions) {
        this.perfilopcions = perfilopcions;
    }
    public Set<Usuarioperfil> getUsuarioperfils() {
        return this.usuarioperfils;
    }
    
    public void setUsuarioperfils(Set<Usuarioperfil> usuarioperfils) {
        this.usuarioperfils = usuarioperfils;
    }




}


