package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Puntoacumulado generated by hbm2java
 */
public class Puntoacumulado  implements java.io.Serializable {


     private PuntoacumuladoId id;
     private Tarjeta tarjeta;
     private Transaccion transaccion;
     private Date fechaRegistro;
     private Integer numeroPuntos;

    public Puntoacumulado() {
    }

	
    public Puntoacumulado(PuntoacumuladoId id, Tarjeta tarjeta, Transaccion transaccion) {
        this.id = id;
        this.tarjeta = tarjeta;
        this.transaccion = transaccion;
    }
    public Puntoacumulado(PuntoacumuladoId id, Tarjeta tarjeta, Transaccion transaccion, Date fechaRegistro, Integer numeroPuntos) {
       this.id = id;
       this.tarjeta = tarjeta;
       this.transaccion = transaccion;
       this.fechaRegistro = fechaRegistro;
       this.numeroPuntos = numeroPuntos;
    }
   
    public PuntoacumuladoId getId() {
        return this.id;
    }
    
    public void setId(PuntoacumuladoId id) {
        this.id = id;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }
    public Transaccion getTransaccion() {
        return this.transaccion;
    }
    
    public void setTransaccion(Transaccion transaccion) {
        this.transaccion = transaccion;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Integer getNumeroPuntos() {
        return this.numeroPuntos;
    }
    
    public void setNumeroPuntos(Integer numeroPuntos) {
        this.numeroPuntos = numeroPuntos;
    }




}


