package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Surtidor generated by hbm2java
 */
public class Surtidor  implements java.io.Serializable {


     private int id;
     private Estacionservicio estacionservicio;
     private Integer idMarca;
     private Integer idModelo;
     private String descripcion;
     private String nombre;
     private Integer nroCaras;
     private String numeroSerie;
     private Date fechaRegistro;
     private Integer idFamiliaElectronica;
     private Integer nroMangueras;
     private String lote;
     private Set<Cara> caras = new HashSet<Cara>(0);

    public Surtidor() {
    }

	
    public Surtidor(int id, Estacionservicio estacionservicio) {
        this.id = id;
        this.estacionservicio = estacionservicio;
    }
    public Surtidor(int id, Estacionservicio estacionservicio, Integer idMarca, Integer idModelo, String descripcion, String nombre, Integer nroCaras, String numeroSerie, Date fechaRegistro, Integer idFamiliaElectronica, Integer nroMangueras, String lote, Set<Cara> caras) {
       this.id = id;
       this.estacionservicio = estacionservicio;
       this.idMarca = idMarca;
       this.idModelo = idModelo;
       this.descripcion = descripcion;
       this.nombre = nombre;
       this.nroCaras = nroCaras;
       this.numeroSerie = numeroSerie;
       this.fechaRegistro = fechaRegistro;
       this.idFamiliaElectronica = idFamiliaElectronica;
       this.nroMangueras = nroMangueras;
       this.lote = lote;
       this.caras = caras;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Estacionservicio getEstacionservicio() {
        return this.estacionservicio;
    }
    
    public void setEstacionservicio(Estacionservicio estacionservicio) {
        this.estacionservicio = estacionservicio;
    }
    public Integer getIdMarca() {
        return this.idMarca;
    }
    
    public void setIdMarca(Integer idMarca) {
        this.idMarca = idMarca;
    }
    public Integer getIdModelo() {
        return this.idModelo;
    }
    
    public void setIdModelo(Integer idModelo) {
        this.idModelo = idModelo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getNroCaras() {
        return this.nroCaras;
    }
    
    public void setNroCaras(Integer nroCaras) {
        this.nroCaras = nroCaras;
    }
    public String getNumeroSerie() {
        return this.numeroSerie;
    }
    
    public void setNumeroSerie(String numeroSerie) {
        this.numeroSerie = numeroSerie;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Integer getIdFamiliaElectronica() {
        return this.idFamiliaElectronica;
    }
    
    public void setIdFamiliaElectronica(Integer idFamiliaElectronica) {
        this.idFamiliaElectronica = idFamiliaElectronica;
    }
    public Integer getNroMangueras() {
        return this.nroMangueras;
    }
    
    public void setNroMangueras(Integer nroMangueras) {
        this.nroMangueras = nroMangueras;
    }
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }
    public Set<Cara> getCaras() {
        return this.caras;
    }
    
    public void setCaras(Set<Cara> caras) {
        this.caras = caras;
    }




}


