package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transaccion generated by hbm2java
 */
public class Transaccion  implements java.io.Serializable {


     private int id;
     private Cliente cliente;
     private Despacho despacho;
     private Integer idTipoTransaccion;
     private Integer idEstado;
     private String numeroTransaccion;
     private String numeroPlaca;
     private String numeroVale;
     private Long montoTotal;
     private Date fechaRegistro;
     private Set<Transacciondetalle> transacciondetalles = new HashSet<Transacciondetalle>(0);
     private Set<Puntoacumulado> puntoacumulados = new HashSet<Puntoacumulado>(0);
     private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);

    public Transaccion() {
    }

	
    public Transaccion(int id, Cliente cliente, Despacho despacho) {
        this.id = id;
        this.cliente = cliente;
        this.despacho = despacho;
    }
    public Transaccion(int id, Cliente cliente, Despacho despacho, Integer idTipoTransaccion, Integer idEstado, String numeroTransaccion, String numeroPlaca, String numeroVale, Long montoTotal, Date fechaRegistro, Set<Transacciondetalle> transacciondetalles, Set<Puntoacumulado> puntoacumulados, Set<Movimiento> movimientos) {
       this.id = id;
       this.cliente = cliente;
       this.despacho = despacho;
       this.idTipoTransaccion = idTipoTransaccion;
       this.idEstado = idEstado;
       this.numeroTransaccion = numeroTransaccion;
       this.numeroPlaca = numeroPlaca;
       this.numeroVale = numeroVale;
       this.montoTotal = montoTotal;
       this.fechaRegistro = fechaRegistro;
       this.transacciondetalles = transacciondetalles;
       this.puntoacumulados = puntoacumulados;
       this.movimientos = movimientos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Despacho getDespacho() {
        return this.despacho;
    }
    
    public void setDespacho(Despacho despacho) {
        this.despacho = despacho;
    }
    public Integer getIdTipoTransaccion() {
        return this.idTipoTransaccion;
    }
    
    public void setIdTipoTransaccion(Integer idTipoTransaccion) {
        this.idTipoTransaccion = idTipoTransaccion;
    }
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
    public String getNumeroTransaccion() {
        return this.numeroTransaccion;
    }
    
    public void setNumeroTransaccion(String numeroTransaccion) {
        this.numeroTransaccion = numeroTransaccion;
    }
    public String getNumeroPlaca() {
        return this.numeroPlaca;
    }
    
    public void setNumeroPlaca(String numeroPlaca) {
        this.numeroPlaca = numeroPlaca;
    }
    public String getNumeroVale() {
        return this.numeroVale;
    }
    
    public void setNumeroVale(String numeroVale) {
        this.numeroVale = numeroVale;
    }
    public Long getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(Long montoTotal) {
        this.montoTotal = montoTotal;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<Transacciondetalle> getTransacciondetalles() {
        return this.transacciondetalles;
    }
    
    public void setTransacciondetalles(Set<Transacciondetalle> transacciondetalles) {
        this.transacciondetalles = transacciondetalles;
    }
    public Set<Puntoacumulado> getPuntoacumulados() {
        return this.puntoacumulados;
    }
    
    public void setPuntoacumulados(Set<Puntoacumulado> puntoacumulados) {
        this.puntoacumulados = puntoacumulados;
    }
    public Set<Movimiento> getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set<Movimiento> movimientos) {
        this.movimientos = movimientos;
    }




}


