/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.com.ega.sgces.view;

import org.apache.log4j.Logger;
import Imprimir.ImprimirComprobante;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import pe.com.ega.sgces.dao.ClienteDaoImpl;
import pe.com.ega.sgces.dao.DespachoDaoImpl;
import pe.com.ega.sgces.dao.TransaccionDaoImpl;
import pe.com.ega.sgces.logic.ClienteLogicaImpl;
import pe.com.ega.sgces.logic.DespachoLogicaImpl;
import pe.com.ega.sgces.logic.TransaccionLogicaImpl;
import pe.com.ega.sgces.model.Cliente;
import pe.com.ega.sgces.model.Despacho;
import pe.com.ega.sgces.model.Transaccion;

/**
 *
 * @author FLOPEZ
 */
public class ClienteFrame extends org.openswing.swing.mdi.client.InternalFrame {

    private final static Logger logger = Logger.getLogger(ClienteFrame.class);
    private Despacho desp;
    private ClienteLogicaImpl clienteDao;
    private Cliente cliente;
    private Cliente temporal;
    private ImprimirComprobante comprobante;
    private Transaccion transaccion;
    private TransaccionLogicaImpl transaccionDao;
    private DespachoLogicaImpl despachoDao;
    
    public ClienteFrame(Despacho despacho) {
        initComponents();
        desp=despacho;
        clienteDao=new ClienteLogicaImpl();
        clienteDao.setClienteDao(new ClienteDaoImpl());
        transaccion=new Transaccion();
        transaccionDao =new TransaccionLogicaImpl();
        transaccionDao.setTransaccionDao(new TransaccionDaoImpl());
        despachoDao=new DespachoLogicaImpl();
        despachoDao.setDespachoDao(new DespachoDaoImpl());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jrucCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jrazonCliente = new javax.swing.JTextField();
        Registrar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        jPanel1.setLayout(null);

        jLabel1.setText("Razon Social :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 60, 80, 16);

        jrucCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrucClienteActionPerformed(evt);
            }
        });
        jrucCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jrucClienteFocusGained(evt);
            }
        });
        jPanel1.add(jrucCliente);
        jrucCliente.setBounds(100, 30, 170, 22);

        jLabel2.setText("R.U.C");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 30, 34, 16);
        jPanel1.add(jrazonCliente);
        jrazonCliente.setBounds(100, 60, 260, 22);

        Registrar.setText("Grabar");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(Registrar);
        Registrar.setBounds(90, 90, 100, 25);

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar);
        cancelar.setBounds(200, 90, 110, 25);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jrucClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrucClienteActionPerformed
        
    }//GEN-LAST:event_jrucClienteActionPerformed

    private void jrucClienteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jrucClienteFocusGained
        jrucCliente.setText("");
        jrazonCliente.setText("");
    }//GEN-LAST:event_jrucClienteFocusGained

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed

           Cliente temporal1 = new Cliente();
           temporal1.setNumerodocumento(jrucCliente.getText());
           temporal1.setRazonsocial(jrazonCliente.getText());
           if(clienteDao.buscarPorCodigo(jrucCliente.getText())!=null)
           {    
            JOptionPane.showMessageDialog(null, "Cliente Ya existe", "Error", JOptionPane.ERROR_MESSAGE);
                         }else{
               if (jrucCliente.getText().isEmpty() || jrazonCliente.getText().isEmpty()){
                   JOptionPane.showMessageDialog(null, "Faltan Datos", "Error", JOptionPane.ERROR_MESSAGE);
                   
           
           }  else{
                   try {
               clienteDao.grabar(temporal1);
               limpiar();
               salir(evt);
           } catch (Exception e) {
               logger.error("Mensaje:\n"+e.getMessage());
                JOptionPane.showMessageDialog(null, "Error al Grabar", "Error", JOptionPane.ERROR_MESSAGE);
                     
           }
               }            
           }
           
       
    }//GEN-LAST:event_RegistrarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        salir(evt);
    }//GEN-LAST:event_cancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Registrar;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jrazonCliente;
    private javax.swing.JTextField jrucCliente;
    // End of variables declaration//GEN-END:variables
    private void salir (java.awt.event.ActionEvent evt){
       actionPerformed(evt);
   }

    private void actionPerformed(ActionEvent evt) {
        setVisible(false);
        dispose();
    }
    
    public double Redondear(double numero)
{
       int cifras=(int) Math.pow(10,2);
        return Math.rint(numero*cifras)/cifras;
}
    
    public void limpiar(){
        jrucCliente.setText("");
        jrazonCliente.setText("");
    
    }
   

}
