package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cara generated by hbm2java
 */
public class Cara  implements java.io.Serializable {


     private int id;
     private Surtidor surtidor;
     private Date fecharegistro;
     private String codigo;
     private Set<Caraproducto> caraproductos = new HashSet<Caraproducto>(0);

    public Cara() {
    }

	
    public Cara(int id, Surtidor surtidor) {
        this.id = id;
        this.surtidor = surtidor;
    }
    public Cara(int id, Surtidor surtidor, Date fecharegistro, String codigo, Set<Caraproducto> caraproductos) {
       this.id = id;
       this.surtidor = surtidor;
       this.fecharegistro = fecharegistro;
       this.codigo = codigo;
       this.caraproductos = caraproductos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Surtidor getSurtidor() {
        return this.surtidor;
    }
    
    public void setSurtidor(Surtidor surtidor) {
        this.surtidor = surtidor;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set<Caraproducto> getCaraproductos() {
        return this.caraproductos;
    }
    
    public void setCaraproductos(Set<Caraproducto> caraproductos) {
        this.caraproductos = caraproductos;
    }




}


