package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private int id;
     private Cliente cliente;
     private Integer tieneLimiteCredito;
     private Integer tieneLimiteDiario;
     private Integer periodoFacturacion;
     private Integer idTipoPeriodoFacturacion;
     private Integer nroDiasVencimiento;
     private Date fechaRegistro;
     private Integer limiteCredito;
     private Integer limiteDiario;
     private Set<Subcuenta> subcuentas = new HashSet<Subcuenta>(0);

    public Cuenta() {
    }

	
    public Cuenta(int id, Cliente cliente) {
        this.id = id;
        this.cliente = cliente;
    }
    public Cuenta(int id, Cliente cliente, Integer tieneLimiteCredito, Integer tieneLimiteDiario, Integer periodoFacturacion, Integer idTipoPeriodoFacturacion, Integer nroDiasVencimiento, Date fechaRegistro, Integer limiteCredito, Integer limiteDiario, Set<Subcuenta> subcuentas) {
       this.id = id;
       this.cliente = cliente;
       this.tieneLimiteCredito = tieneLimiteCredito;
       this.tieneLimiteDiario = tieneLimiteDiario;
       this.periodoFacturacion = periodoFacturacion;
       this.idTipoPeriodoFacturacion = idTipoPeriodoFacturacion;
       this.nroDiasVencimiento = nroDiasVencimiento;
       this.fechaRegistro = fechaRegistro;
       this.limiteCredito = limiteCredito;
       this.limiteDiario = limiteDiario;
       this.subcuentas = subcuentas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Integer getTieneLimiteCredito() {
        return this.tieneLimiteCredito;
    }
    
    public void setTieneLimiteCredito(Integer tieneLimiteCredito) {
        this.tieneLimiteCredito = tieneLimiteCredito;
    }
    public Integer getTieneLimiteDiario() {
        return this.tieneLimiteDiario;
    }
    
    public void setTieneLimiteDiario(Integer tieneLimiteDiario) {
        this.tieneLimiteDiario = tieneLimiteDiario;
    }
    public Integer getPeriodoFacturacion() {
        return this.periodoFacturacion;
    }
    
    public void setPeriodoFacturacion(Integer periodoFacturacion) {
        this.periodoFacturacion = periodoFacturacion;
    }
    public Integer getIdTipoPeriodoFacturacion() {
        return this.idTipoPeriodoFacturacion;
    }
    
    public void setIdTipoPeriodoFacturacion(Integer idTipoPeriodoFacturacion) {
        this.idTipoPeriodoFacturacion = idTipoPeriodoFacturacion;
    }
    public Integer getNroDiasVencimiento() {
        return this.nroDiasVencimiento;
    }
    
    public void setNroDiasVencimiento(Integer nroDiasVencimiento) {
        this.nroDiasVencimiento = nroDiasVencimiento;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Integer getLimiteCredito() {
        return this.limiteCredito;
    }
    
    public void setLimiteCredito(Integer limiteCredito) {
        this.limiteCredito = limiteCredito;
    }
    public Integer getLimiteDiario() {
        return this.limiteDiario;
    }
    
    public void setLimiteDiario(Integer limiteDiario) {
        this.limiteDiario = limiteDiario;
    }
    public Set<Subcuenta> getSubcuentas() {
        return this.subcuentas;
    }
    
    public void setSubcuentas(Set<Subcuenta> subcuentas) {
        this.subcuentas = subcuentas;
    }




}


