package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Deposito generated by hbm2java
 */
public class Deposito  implements java.io.Serializable {


     private int id;
     private Turnopuntoventacaja turnopuntoventacaja;
     private Long montototal;
     private Date fecharegistro;
     private Integer idtipopago;

    public Deposito() {
    }

	
    public Deposito(int id, Turnopuntoventacaja turnopuntoventacaja) {
        this.id = id;
        this.turnopuntoventacaja = turnopuntoventacaja;
    }
    public Deposito(int id, Turnopuntoventacaja turnopuntoventacaja, Long montototal, Date fecharegistro, Integer idtipopago) {
       this.id = id;
       this.turnopuntoventacaja = turnopuntoventacaja;
       this.montototal = montototal;
       this.fecharegistro = fecharegistro;
       this.idtipopago = idtipopago;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Turnopuntoventacaja getTurnopuntoventacaja() {
        return this.turnopuntoventacaja;
    }
    
    public void setTurnopuntoventacaja(Turnopuntoventacaja turnopuntoventacaja) {
        this.turnopuntoventacaja = turnopuntoventacaja;
    }
    public Long getMontototal() {
        return this.montototal;
    }
    
    public void setMontototal(Long montototal) {
        this.montototal = montototal;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Integer getIdtipopago() {
        return this.idtipopago;
    }
    
    public void setIdtipopago(Integer idtipopago) {
        this.idtipopago = idtipopago;
    }




}


