package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Distrito generated by hbm2java
 */
public class Distrito  implements java.io.Serializable {


     private DistritoId id;
     private Provincia provincia;
     private String nombre;
     private Set<Estacionservicio> estacionservicios = new HashSet<Estacionservicio>(0);

    public Distrito() {
    }

	
    public Distrito(DistritoId id, Provincia provincia) {
        this.id = id;
        this.provincia = provincia;
    }
    public Distrito(DistritoId id, Provincia provincia, String nombre, Set<Estacionservicio> estacionservicios) {
       this.id = id;
       this.provincia = provincia;
       this.nombre = nombre;
       this.estacionservicios = estacionservicios;
    }
   
    public DistritoId getId() {
        return this.id;
    }
    
    public void setId(DistritoId id) {
        this.id = id;
    }
    public Provincia getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(Provincia provincia) {
        this.provincia = provincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Estacionservicio> getEstacionservicios() {
        return this.estacionservicios;
    }
    
    public void setEstacionservicios(Set<Estacionservicio> estacionservicios) {
        this.estacionservicios = estacionservicios;
    }




}


