package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA



/**
 * ImpresorapuntoventaId generated by hbm2java
 */
public class ImpresorapuntoventaId  implements java.io.Serializable {


     private int idPuntoVenta;
     private int idImpresora;

    public ImpresorapuntoventaId() {
    }

    public ImpresorapuntoventaId(int idPuntoVenta, int idImpresora) {
       this.idPuntoVenta = idPuntoVenta;
       this.idImpresora = idImpresora;
    }
   
    public int getIdPuntoVenta() {
        return this.idPuntoVenta;
    }
    
    public void setIdPuntoVenta(int idPuntoVenta) {
        this.idPuntoVenta = idPuntoVenta;
    }
    public int getIdImpresora() {
        return this.idImpresora;
    }
    
    public void setIdImpresora(int idImpresora) {
        this.idImpresora = idImpresora;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ImpresorapuntoventaId) ) return false;
		 ImpresorapuntoventaId castOther = ( ImpresorapuntoventaId ) other; 
         
		 return (this.getIdPuntoVenta()==castOther.getIdPuntoVenta())
 && (this.getIdImpresora()==castOther.getIdImpresora());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdPuntoVenta();
         result = 37 * result + this.getIdImpresora();
         return result;
   }   


}


