package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Movimiento generated by hbm2java
 */
public class Movimiento  implements java.io.Serializable {


     private int id;
     private Turnopuntoventacaja turnopuntoventacaja;
     private Transaccion transaccion;
     private String pago;
     private Double montorecibido;
     private Double montototal;
     private Double montodevuelto;
     private Date fecharegistro;
     private String nrooperacion;

    public Movimiento() {
    }

	
    public Movimiento(int id, Turnopuntoventacaja turnopuntoventacaja, Transaccion transaccion) {
        this.id = id;
        this.turnopuntoventacaja = turnopuntoventacaja;
        this.transaccion = transaccion;
    }
    public Movimiento(int id, Turnopuntoventacaja turnopuntoventacaja, Transaccion transaccion, String pago, Double montorecibido, Double montototal, Double montodevuelto, Date fecharegistro, String nrooperacion) {
       this.id = id;
       this.turnopuntoventacaja = turnopuntoventacaja;
       this.transaccion = transaccion;
       this.pago = pago;
       this.montorecibido = montorecibido;
       this.montototal = montototal;
       this.montodevuelto = montodevuelto;
       this.fecharegistro = fecharegistro;
       this.nrooperacion = nrooperacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Turnopuntoventacaja getTurnopuntoventacaja() {
        return this.turnopuntoventacaja;
    }
    
    public void setTurnopuntoventacaja(Turnopuntoventacaja turnopuntoventacaja) {
        this.turnopuntoventacaja = turnopuntoventacaja;
    }
    public Transaccion getTransaccion() {
        return this.transaccion;
    }
    
    public void setTransaccion(Transaccion transaccion) {
        this.transaccion = transaccion;
    }
    public String getPago() {
        return this.pago;
    }
    
    public void setPago(String pago) {
        this.pago = pago;
    }
    public Double getMontorecibido() {
        return this.montorecibido;
    }
    
    public void setMontorecibido(Double montorecibido) {
        this.montorecibido = montorecibido;
    }
    public Double getMontototal() {
        return this.montototal;
    }
    
    public void setMontototal(Double montototal) {
        this.montototal = montototal;
    }
    public Double getMontodevuelto() {
        return this.montodevuelto;
    }
    
    public void setMontodevuelto(Double montodevuelto) {
        this.montodevuelto = montodevuelto;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public String getNrooperacion() {
        return this.nrooperacion;
    }
    
    public void setNrooperacion(String nrooperacion) {
        this.nrooperacion = nrooperacion;
    }




}


