package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int id;
     private Integer idTipoProducto;
     private String nombre;
     private Date fechaRegistro;
     private Set<Subcuenta> subcuentas = new HashSet<Subcuenta>(0);
     private Set<Caraproducto> caraproductos = new HashSet<Caraproducto>(0);
     private Set<Tanque> tanques = new HashSet<Tanque>(0);
     private Set<Transacciondetalle> transacciondetalles = new HashSet<Transacciondetalle>(0);
     private Set<Despacho> despachos = new HashSet<Despacho>(0);

    public Producto() {
    }

	
    public Producto(int id) {
        this.id = id;
    }
    public Producto(int id, Integer idTipoProducto, String nombre, Date fechaRegistro, Set<Subcuenta> subcuentas, Set<Caraproducto> caraproductos, Set<Tanque> tanques, Set<Transacciondetalle> transacciondetalles, Set<Despacho> despachos) {
       this.id = id;
       this.idTipoProducto = idTipoProducto;
       this.nombre = nombre;
       this.fechaRegistro = fechaRegistro;
       this.subcuentas = subcuentas;
       this.caraproductos = caraproductos;
       this.tanques = tanques;
       this.transacciondetalles = transacciondetalles;
       this.despachos = despachos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getIdTipoProducto() {
        return this.idTipoProducto;
    }
    
    public void setIdTipoProducto(Integer idTipoProducto) {
        this.idTipoProducto = idTipoProducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<Subcuenta> getSubcuentas() {
        return this.subcuentas;
    }
    
    public void setSubcuentas(Set<Subcuenta> subcuentas) {
        this.subcuentas = subcuentas;
    }
    public Set<Caraproducto> getCaraproductos() {
        return this.caraproductos;
    }
    
    public void setCaraproductos(Set<Caraproducto> caraproductos) {
        this.caraproductos = caraproductos;
    }
    public Set<Tanque> getTanques() {
        return this.tanques;
    }
    
    public void setTanques(Set<Tanque> tanques) {
        this.tanques = tanques;
    }
    public Set<Transacciondetalle> getTransacciondetalles() {
        return this.transacciondetalles;
    }
    
    public void setTransacciondetalles(Set<Transacciondetalle> transacciondetalles) {
        this.transacciondetalles = transacciondetalles;
    }
    public Set<Despacho> getDespachos() {
        return this.despachos;
    }
    
    public void setDespachos(Set<Despacho> despachos) {
        this.despachos = despachos;
    }




}


