package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA



/**
 * ProvinciaId generated by hbm2java
 */
public class ProvinciaId  implements java.io.Serializable {


     private String id;
     private String iddepartamento;

    public ProvinciaId() {
    }

    public ProvinciaId(String id, String iddepartamento) {
       this.id = id;
       this.iddepartamento = iddepartamento;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(String iddepartamento) {
        this.iddepartamento = iddepartamento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProvinciaId) ) return false;
		 ProvinciaId castOther = ( ProvinciaId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getIddepartamento()==castOther.getIddepartamento()) || ( this.getIddepartamento()!=null && castOther.getIddepartamento()!=null && this.getIddepartamento().equals(castOther.getIddepartamento()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getIddepartamento() == null ? 0 : this.getIddepartamento().hashCode() );
         return result;
   }   


}


