package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Puntoventa generated by hbm2java
 */
public class Puntoventa  implements java.io.Serializable {


     private int id;
     private Estacionservicio estacionservicio;
     private String nombre;
     private String descripcion;
     private Integer idtipopuntoventa;
     private Date fecharegistro;
     private Set<Turnopuntoventacaja> turnopuntoventacajas = new HashSet<Turnopuntoventacaja>(0);
     private Set<Impresorapuntoventa> impresorapuntoventas = new HashSet<Impresorapuntoventa>(0);
     private Set<Centroemisor> centroemisors = new HashSet<Centroemisor>(0);

    public Puntoventa() {
    }

	
    public Puntoventa(int id, Estacionservicio estacionservicio) {
        this.id = id;
        this.estacionservicio = estacionservicio;
    }
    public Puntoventa(int id, Estacionservicio estacionservicio, String nombre, String descripcion, Integer idtipopuntoventa, Date fecharegistro, Set<Turnopuntoventacaja> turnopuntoventacajas, Set<Impresorapuntoventa> impresorapuntoventas, Set<Centroemisor> centroemisors) {
       this.id = id;
       this.estacionservicio = estacionservicio;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.idtipopuntoventa = idtipopuntoventa;
       this.fecharegistro = fecharegistro;
       this.turnopuntoventacajas = turnopuntoventacajas;
       this.impresorapuntoventas = impresorapuntoventas;
       this.centroemisors = centroemisors;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Estacionservicio getEstacionservicio() {
        return this.estacionservicio;
    }
    
    public void setEstacionservicio(Estacionservicio estacionservicio) {
        this.estacionservicio = estacionservicio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getIdtipopuntoventa() {
        return this.idtipopuntoventa;
    }
    
    public void setIdtipopuntoventa(Integer idtipopuntoventa) {
        this.idtipopuntoventa = idtipopuntoventa;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Set<Turnopuntoventacaja> getTurnopuntoventacajas() {
        return this.turnopuntoventacajas;
    }
    
    public void setTurnopuntoventacajas(Set<Turnopuntoventacaja> turnopuntoventacajas) {
        this.turnopuntoventacajas = turnopuntoventacajas;
    }
    public Set<Impresorapuntoventa> getImpresorapuntoventas() {
        return this.impresorapuntoventas;
    }
    
    public void setImpresorapuntoventas(Set<Impresorapuntoventa> impresorapuntoventas) {
        this.impresorapuntoventas = impresorapuntoventas;
    }
    public Set<Centroemisor> getCentroemisors() {
        return this.centroemisors;
    }
    
    public void setCentroemisors(Set<Centroemisor> centroemisors) {
        this.centroemisors = centroemisors;
    }




}


