package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Puntoventa generated by hbm2java
 */
public class Puntoventa  implements java.io.Serializable {


     private int id;
     private Estacionservicio estacionservicio;
     private String nombre;
     private String descripcion;
     private Integer idTipoPuntoVenta;
     private Date fechaRegistro;
     private Set<Turnopuntoventacaja> turnopuntoventacajas = new HashSet<Turnopuntoventacaja>(0);
     private Set<Impresorapuntoventa> impresorapuntoventas = new HashSet<Impresorapuntoventa>(0);
     private Set<Centroemisor> centroemisors = new HashSet<Centroemisor>(0);

    public Puntoventa() {
    }

	
    public Puntoventa(int id, Estacionservicio estacionservicio) {
        this.id = id;
        this.estacionservicio = estacionservicio;
    }
    public Puntoventa(int id, Estacionservicio estacionservicio, String nombre, String descripcion, Integer idTipoPuntoVenta, Date fechaRegistro, Set<Turnopuntoventacaja> turnopuntoventacajas, Set<Impresorapuntoventa> impresorapuntoventas, Set<Centroemisor> centroemisors) {
       this.id = id;
       this.estacionservicio = estacionservicio;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.idTipoPuntoVenta = idTipoPuntoVenta;
       this.fechaRegistro = fechaRegistro;
       this.turnopuntoventacajas = turnopuntoventacajas;
       this.impresorapuntoventas = impresorapuntoventas;
       this.centroemisors = centroemisors;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Estacionservicio getEstacionservicio() {
        return this.estacionservicio;
    }
    
    public void setEstacionservicio(Estacionservicio estacionservicio) {
        this.estacionservicio = estacionservicio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getIdTipoPuntoVenta() {
        return this.idTipoPuntoVenta;
    }
    
    public void setIdTipoPuntoVenta(Integer idTipoPuntoVenta) {
        this.idTipoPuntoVenta = idTipoPuntoVenta;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<Turnopuntoventacaja> getTurnopuntoventacajas() {
        return this.turnopuntoventacajas;
    }
    
    public void setTurnopuntoventacajas(Set<Turnopuntoventacaja> turnopuntoventacajas) {
        this.turnopuntoventacajas = turnopuntoventacajas;
    }
    public Set<Impresorapuntoventa> getImpresorapuntoventas() {
        return this.impresorapuntoventas;
    }
    
    public void setImpresorapuntoventas(Set<Impresorapuntoventa> impresorapuntoventas) {
        this.impresorapuntoventas = impresorapuntoventas;
    }
    public Set<Centroemisor> getCentroemisors() {
        return this.centroemisors;
    }
    
    public void setCentroemisors(Set<Centroemisor> centroemisors) {
        this.centroemisors = centroemisors;
    }




}


