package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transaccion generated by hbm2java
 */
public class Transaccion  implements java.io.Serializable {


     private int id;
     private Cliente cliente;
     private Despacho despacho;
     private String idTipoTransaccion;
     private Integer idEstado;
     private Integer numero;
     private String numeroTransaccion;
     private String numeroPlaca;
     private String numeroVale;
     private String numeroTiket;
     private String producto;
     private Double montoTotal;
     private Double nroGalones;
     private Double precioUnitario;
     private Date fechaRegistro;
     private Set<Transacciondetalle> transacciondetalles = new HashSet<Transacciondetalle>(0);
     private Set<Puntoacumulado> puntoacumulados = new HashSet<Puntoacumulado>(0);
     private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);

    public Transaccion() {
    }

    public Transaccion(int id, Cliente cliente, Despacho despacho, String idTipoTransaccion, Integer idEstado, String numeroTransaccion, String numeroPlaca, String numeroVale, String numeroTiket, String producto, Double montoTotal, Double nroGalones, Double precioUnitario, Date fechaRegistro) {
        this.id = id;
        this.cliente = cliente;
        this.despacho = despacho;
        this.idTipoTransaccion = idTipoTransaccion;
        this.idEstado = idEstado;
        this.numeroTransaccion = numeroTransaccion;
        this.numeroPlaca = numeroPlaca;
        this.numeroVale = numeroVale;
        this.numeroTiket = numeroTiket;
        this.producto = producto;
        this.montoTotal = montoTotal;
        this.nroGalones = nroGalones;
        this.precioUnitario = precioUnitario;
        this.fechaRegistro = fechaRegistro;
    }

    
	
    public Transaccion(int id, Cliente cliente, Despacho despacho) {
        this.id = id;
        this.cliente = cliente;
        this.despacho = despacho;
    }
    
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Despacho getDespacho() {
        return this.despacho;
    }
    
    public void setDespacho(Despacho despacho) {
        this.despacho = despacho;
    }
    public String getIdTipoTransaccion() {
        return this.idTipoTransaccion;
    }
    
    public void setIdTipoTransaccion(String idTipoTransaccion) {
        this.idTipoTransaccion = idTipoTransaccion;
    }
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
    public String getNumeroTransaccion() {
        return this.numeroTransaccion;
    }
    
    public void setNumeroTransaccion(String numeroTransaccion) {
        this.numeroTransaccion = numeroTransaccion;
    }
    public String getNumeroPlaca() {
        return this.numeroPlaca;
    }
    
    public void setNumeroPlaca(String numeroPlaca) {
        this.numeroPlaca = numeroPlaca;
    }
    public String getNumeroVale() {
        return this.numeroVale;
    }
    
    public void setNumeroVale(String numeroVale) {
        this.numeroVale = numeroVale;
    }
    public Double getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(Double montoTotal) {
        this.montoTotal = montoTotal;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<Transacciondetalle> getTransacciondetalles() {
        return this.transacciondetalles;
    }
    
    public void setTransacciondetalles(Set<Transacciondetalle> transacciondetalles) {
        this.transacciondetalles = transacciondetalles;
    }
    public Set<Puntoacumulado> getPuntoacumulados() {
        return this.puntoacumulados;
    }
    
    public void setPuntoacumulados(Set<Puntoacumulado> puntoacumulados) {
        this.puntoacumulados = puntoacumulados;
    }
    public Set<Movimiento> getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set<Movimiento> movimientos) {
        this.movimientos = movimientos;
    }

    public Double getNroGalones() {
        return nroGalones;
    }

    public void setNroGalones(Double nroGalones) {
        this.nroGalones = nroGalones;
    }

    public Double getPrecioUnitario() {
        return precioUnitario;
    }

    public void setPrecioUnitario(Double precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    
    public String getProducto() {
        return producto;
    }

    public void setProducto(String producto) {
        this.producto = producto;
    }
    
    public String getNumeroTiket() {
        return numeroTiket;
    }

    public void setNumeroTiket(String numeroTiket) {
        this.numeroTiket = numeroTiket;
    }
    
    
    public Integer getNumero() {
        return numero;
    }

    public void setNumero(Integer numero) {
        this.numero = numero;
    }

}


