package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA



/**
 * TurnopuntoventacajaId generated by hbm2java
 */
public class TurnopuntoventacajaId  implements java.io.Serializable {


     private int idturno;
     private int idpuntoventa;
     private int idcaja;

    public TurnopuntoventacajaId() {
    }

    public TurnopuntoventacajaId(int idturno, int idpuntoventa, int idcaja) {
       this.idturno = idturno;
       this.idpuntoventa = idpuntoventa;
       this.idcaja = idcaja;
    }
   
    public int getIdturno() {
        return this.idturno;
    }
    
    public void setIdturno(int idturno) {
        this.idturno = idturno;
    }
    public int getIdpuntoventa() {
        return this.idpuntoventa;
    }
    
    public void setIdpuntoventa(int idpuntoventa) {
        this.idpuntoventa = idpuntoventa;
    }
    public int getIdcaja() {
        return this.idcaja;
    }
    
    public void setIdcaja(int idcaja) {
        this.idcaja = idcaja;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TurnopuntoventacajaId) ) return false;
		 TurnopuntoventacajaId castOther = ( TurnopuntoventacajaId ) other; 
         
		 return (this.getIdturno()==castOther.getIdturno())
 && (this.getIdpuntoventa()==castOther.getIdpuntoventa())
 && (this.getIdcaja()==castOther.getIdcaja());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdturno();
         result = 37 * result + this.getIdpuntoventa();
         result = 37 * result + this.getIdcaja();
         return result;
   }   


}


