package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Turno generated by hbm2java
 */
public class Turno  implements java.io.Serializable {


     private int id;
     private Estacionservicio estacionservicio;
     private Date fechaApertura;
     private Date fechaCierre;
     private Set<Turnopuntoventacaja> turnopuntoventacajas = new HashSet<Turnopuntoventacaja>(0);

    public Turno() {
    }

	
    public Turno(int id, Estacionservicio estacionservicio) {
        this.id = id;
        this.estacionservicio = estacionservicio;
    }
    public Turno(int id, Estacionservicio estacionservicio, Date fechaApertura, Date fechaCierre, Set<Turnopuntoventacaja> turnopuntoventacajas) {
       this.id = id;
       this.estacionservicio = estacionservicio;
       this.fechaApertura = fechaApertura;
       this.fechaCierre = fechaCierre;
       this.turnopuntoventacajas = turnopuntoventacajas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Estacionservicio getEstacionservicio() {
        return this.estacionservicio;
    }
    
    public void setEstacionservicio(Estacionservicio estacionservicio) {
        this.estacionservicio = estacionservicio;
    }
    public Date getFechaApertura() {
        return this.fechaApertura;
    }
    
    public void setFechaApertura(Date fechaApertura) {
        this.fechaApertura = fechaApertura;
    }
    public Date getFechaCierre() {
        return this.fechaCierre;
    }
    
    public void setFechaCierre(Date fechaCierre) {
        this.fechaCierre = fechaCierre;
    }
    public Set<Turnopuntoventacaja> getTurnopuntoventacajas() {
        return this.turnopuntoventacajas;
    }
    
    public void setTurnopuntoventacajas(Set<Turnopuntoventacaja> turnopuntoventacajas) {
        this.turnopuntoventacajas = turnopuntoventacajas;
    }




}


