package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Turnopuntoventacaja generated by hbm2java
 */
public class Turnopuntoventacaja  implements java.io.Serializable {


     private TurnopuntoventacajaId id;
     private Caja caja;
     private Turno turno;
     private Puntoventa puntoventa;
     private Date fecharegistro;
     private Set<Deposito> depositos = new HashSet<Deposito>(0);
     private Set<Movimiento> movimientos = new HashSet<Movimiento>(0);

    public Turnopuntoventacaja() {
    }

	
    public Turnopuntoventacaja(TurnopuntoventacajaId id, Caja caja, Turno turno, Puntoventa puntoventa) {
        this.id = id;
        this.caja = caja;
        this.turno = turno;
        this.puntoventa = puntoventa;
    }
    public Turnopuntoventacaja(TurnopuntoventacajaId id, Caja caja, Turno turno, Puntoventa puntoventa, Date fecharegistro, Set<Deposito> depositos, Set<Movimiento> movimientos) {
       this.id = id;
       this.caja = caja;
       this.turno = turno;
       this.puntoventa = puntoventa;
       this.fecharegistro = fecharegistro;
       this.depositos = depositos;
       this.movimientos = movimientos;
    }
   
    public TurnopuntoventacajaId getId() {
        return this.id;
    }
    
    public void setId(TurnopuntoventacajaId id) {
        this.id = id;
    }
    public Caja getCaja() {
        return this.caja;
    }
    
    public void setCaja(Caja caja) {
        this.caja = caja;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public Puntoventa getPuntoventa() {
        return this.puntoventa;
    }
    
    public void setPuntoventa(Puntoventa puntoventa) {
        this.puntoventa = puntoventa;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Set<Deposito> getDepositos() {
        return this.depositos;
    }
    
    public void setDepositos(Set<Deposito> depositos) {
        this.depositos = depositos;
    }
    public Set<Movimiento> getMovimientos() {
        return this.movimientos;
    }
    
    public void setMovimientos(Set<Movimiento> movimientos) {
        this.movimientos = movimientos;
    }




}


