package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Turno generated by hbm2java
 */
public class Turno  implements java.io.Serializable {


     private int id;
     private Estacionservicio estacionservicio;
     private Date fechaapertura;
     private Date fechacierre;
     private Set<Turnopuntoventacaja> turnopuntoventacajas = new HashSet<Turnopuntoventacaja>(0);
     private String estado;

  

    public Turno() {
    }

	
    public Turno(int id, Estacionservicio estacionservicio) {
        this.id = id;
        this.estacionservicio = estacionservicio;
    }
    public Turno(int id, Estacionservicio estacionservicio, Date fechaapertura, Date fechacierre, Set<Turnopuntoventacaja> turnopuntoventacajas, String estado) {
       this.id = id;
       this.estacionservicio = estacionservicio;
       this.fechaapertura = fechaapertura;
       this.fechacierre = fechacierre;
       this.turnopuntoventacajas = turnopuntoventacajas;
       this.estado=estado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Estacionservicio getEstacionservicio() {
        return this.estacionservicio;
    }
    
    public void setEstacionservicio(Estacionservicio estacionservicio) {
        this.estacionservicio = estacionservicio;
    }
    public Date getFechaapertura() {
        return this.fechaapertura;
    }
    
    public void setFechaapertura(Date fechaapertura) {
        this.fechaapertura = fechaapertura;
    }
    public Date getFechacierre() {
        return this.fechacierre;
    }
    
    public void setFechacierre(Date fechacierre) {
        this.fechacierre = fechacierre;
    }
    public Set<Turnopuntoventacaja> getTurnopuntoventacajas() {
        return this.turnopuntoventacajas;
    }
    
    public void setTurnopuntoventacajas(Set<Turnopuntoventacaja> turnopuntoventacajas) {
        this.turnopuntoventacajas = turnopuntoventacajas;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

   


}


