package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int id;
     private Trabajador trabajador;
     private String login;
     private String clave;
     private Date fechaRegistro;
     private Set<Usuarioperfil> usuarioperfils = new HashSet<Usuarioperfil>(0);

    public Usuario() {
    }

	
    public Usuario(int id, Trabajador trabajador) {
        this.id = id;
        this.trabajador = trabajador;
    }
    public Usuario(int id, Trabajador trabajador, String login, String clave, Date fechaRegistro, Set<Usuarioperfil> usuarioperfils) {
       this.id = id;
       this.trabajador = trabajador;
       this.login = login;
       this.clave = clave;
       this.fechaRegistro = fechaRegistro;
       this.usuarioperfils = usuarioperfils;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Trabajador getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(Trabajador trabajador) {
        this.trabajador = trabajador;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<Usuarioperfil> getUsuarioperfils() {
        return this.usuarioperfils;
    }
    
    public void setUsuarioperfils(Set<Usuarioperfil> usuarioperfils) {
        this.usuarioperfils = usuarioperfils;
    }




}


