package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA



/**
 * CaraproductoId generated by hbm2java
 */
public class CaraproductoId  implements java.io.Serializable {


     private int idcara;
     private int idproducto;

    public CaraproductoId() {
    }

    public CaraproductoId(int idcara, int idproducto) {
       this.idcara = idcara;
       this.idproducto = idproducto;
    }
   
    public int getIdcara() {
        return this.idcara;
    }
    
    public void setIdcara(int idcara) {
        this.idcara = idcara;
    }
    public int getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(int idproducto) {
        this.idproducto = idproducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CaraproductoId) ) return false;
		 CaraproductoId castOther = ( CaraproductoId ) other; 
         
		 return (this.getIdcara()==castOther.getIdcara())
 && (this.getIdproducto()==castOther.getIdproducto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdcara();
         result = 37 * result + this.getIdproducto();
         return result;
   }   


}


