package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cuenta generated by hbm2java
 */
public class Cuenta  implements java.io.Serializable {


     private int id;
     private Cliente cliente;
     private Integer tienelimitecredito;
     private Integer tienelimitediario;
     private Integer periodofacturacion;
     private Integer idtipoperiodofacturacion;
     private Integer nrodiasvencimiento;
     private Date fecharegistro;
     private Integer limitecredito;
     private Integer limitediario;
     private Set<Subcuenta> subcuentas = new HashSet<Subcuenta>(0);

    public Cuenta() {
    }

	
    public Cuenta(int id, Cliente cliente) {
        this.id = id;
        this.cliente = cliente;
    }
    public Cuenta(int id, Cliente cliente, Integer tienelimitecredito, Integer tienelimitediario, Integer periodofacturacion, Integer idtipoperiodofacturacion, Integer nrodiasvencimiento, Date fecharegistro, Integer limitecredito, Integer limitediario, Set<Subcuenta> subcuentas) {
       this.id = id;
       this.cliente = cliente;
       this.tienelimitecredito = tienelimitecredito;
       this.tienelimitediario = tienelimitediario;
       this.periodofacturacion = periodofacturacion;
       this.idtipoperiodofacturacion = idtipoperiodofacturacion;
       this.nrodiasvencimiento = nrodiasvencimiento;
       this.fecharegistro = fecharegistro;
       this.limitecredito = limitecredito;
       this.limitediario = limitediario;
       this.subcuentas = subcuentas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Integer getTienelimitecredito() {
        return this.tienelimitecredito;
    }
    
    public void setTienelimitecredito(Integer tienelimitecredito) {
        this.tienelimitecredito = tienelimitecredito;
    }
    public Integer getTienelimitediario() {
        return this.tienelimitediario;
    }
    
    public void setTienelimitediario(Integer tienelimitediario) {
        this.tienelimitediario = tienelimitediario;
    }
    public Integer getPeriodofacturacion() {
        return this.periodofacturacion;
    }
    
    public void setPeriodofacturacion(Integer periodofacturacion) {
        this.periodofacturacion = periodofacturacion;
    }
    public Integer getIdtipoperiodofacturacion() {
        return this.idtipoperiodofacturacion;
    }
    
    public void setIdtipoperiodofacturacion(Integer idtipoperiodofacturacion) {
        this.idtipoperiodofacturacion = idtipoperiodofacturacion;
    }
    public Integer getNrodiasvencimiento() {
        return this.nrodiasvencimiento;
    }
    
    public void setNrodiasvencimiento(Integer nrodiasvencimiento) {
        this.nrodiasvencimiento = nrodiasvencimiento;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Integer getLimitecredito() {
        return this.limitecredito;
    }
    
    public void setLimitecredito(Integer limitecredito) {
        this.limitecredito = limitecredito;
    }
    public Integer getLimitediario() {
        return this.limitediario;
    }
    
    public void setLimitediario(Integer limitediario) {
        this.limitediario = limitediario;
    }
    public Set<Subcuenta> getSubcuentas() {
        return this.subcuentas;
    }
    
    public void setSubcuentas(Set<Subcuenta> subcuentas) {
        this.subcuentas = subcuentas;
    }




}


