package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Impresora generated by hbm2java
 */
public class Impresora  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private String puerto;
     private Date fecharegistro;
     private Set<Impresorapuntoventa> impresorapuntoventas = new HashSet<Impresorapuntoventa>(0);

    public Impresora() {
    }

	
    public Impresora(int id) {
        this.id = id;
    }
    public Impresora(int id, String nombre, String descripcion, String puerto, Date fecharegistro, Set<Impresorapuntoventa> impresorapuntoventas) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.puerto = puerto;
       this.fecharegistro = fecharegistro;
       this.impresorapuntoventas = impresorapuntoventas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getPuerto() {
        return this.puerto;
    }
    
    public void setPuerto(String puerto) {
        this.puerto = puerto;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Set<Impresorapuntoventa> getImpresorapuntoventas() {
        return this.impresorapuntoventas;
    }
    
    public void setImpresorapuntoventas(Set<Impresorapuntoventa> impresorapuntoventas) {
        this.impresorapuntoventas = impresorapuntoventas;
    }




}


