package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA



/**
 * ImpresorapuntoventaId generated by hbm2java
 */
public class ImpresorapuntoventaId  implements java.io.Serializable {


     private int idpuntoventa;
     private int idimpresora;
   
    public int getIdpuntoventa() {
        return this.idpuntoventa;
    }
    
    public void setIdpuntoventa(int idpuntoventa) {
        this.idpuntoventa = idpuntoventa;
    }
    public int getIdimpresora() {
        return this.idimpresora;
    }
    
    public void setIdimpresora(int idimpresora) {
        this.idimpresora = idimpresora;
    }

}


