package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA



/**
 * PerfilopcionId generated by hbm2java
 */
public class PerfilopcionId  implements java.io.Serializable {


     private int idopcion;
     private int idperfil;

    public PerfilopcionId() {
    }

    public int getIdopcion() {
        return this.idopcion;
    }
    
    public void setIdopcion(int idopcion) {
        this.idopcion = idopcion;
    }
    public int getIdperfil() {
        return this.idperfil;
    }
    
    public void setIdperfil(int idperfil) {
        this.idperfil = idperfil;
    }
}


