package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA



/**
 * ProvinciaId generated by hbm2java
 */
public class ProvinciaId  implements java.io.Serializable {


     private String id;
     private String iddepartamento;

    public ProvinciaId() {
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getIddepartamento() {
        return this.iddepartamento;
    }
    
    public void setIddepartamento(String iddepartamento) {
        this.iddepartamento = iddepartamento;
    }
}


