package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Puntoacumulado generated by hbm2java
 */
public class Puntoacumulado  implements java.io.Serializable {


     private PuntoacumuladoId id;
     private Tarjeta tarjeta;
     private Transaccion transaccion;
     private Date fecharegistro;
     private Integer numeropuntos;

    public Puntoacumulado() {
    }

	
    public Puntoacumulado(PuntoacumuladoId id, Tarjeta tarjeta, Transaccion transaccion) {
        this.id = id;
        this.tarjeta = tarjeta;
        this.transaccion = transaccion;
    }
    public Puntoacumulado(PuntoacumuladoId id, Tarjeta tarjeta, Transaccion transaccion, Date fecharegistro, Integer numeropuntos) {
       this.id = id;
       this.tarjeta = tarjeta;
       this.transaccion = transaccion;
       this.fecharegistro = fecharegistro;
       this.numeropuntos = numeropuntos;
    }
   
    public PuntoacumuladoId getId() {
        return this.id;
    }
    
    public void setId(PuntoacumuladoId id) {
        this.id = id;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }
    public Transaccion getTransaccion() {
        return this.transaccion;
    }
    
    public void setTransaccion(Transaccion transaccion) {
        this.transaccion = transaccion;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Integer getNumeropuntos() {
        return this.numeropuntos;
    }
    
    public void setNumeropuntos(Integer numeropuntos) {
        this.numeropuntos = numeropuntos;
    }




}


