package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Surtidor generated by hbm2java
 */
public class Surtidor  implements java.io.Serializable {


     private int id;
     private Estacionservicio estacionservicio;
     private Integer idmarca;
     private Integer idmodelo;
     private String descripcion;
     private String nombre;
     private Integer nrocaras;
     private String numeroserie;
     private Date fecharegistro;
     private Integer idfamiliaelectronica;
     private Integer nromangueras;
     private String lote;
     private Set<Cara> caras = new HashSet<Cara>(0);

    public Surtidor() {
    }

    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Estacionservicio getEstacionservicio() {
        return this.estacionservicio;
    }
    
    public void setEstacionservicio(Estacionservicio estacionservicio) {
        this.estacionservicio = estacionservicio;
    }
    public Integer getIdmarca() {
        return this.idmarca;
    }
    
    public void setIdmarca(Integer idmarca) {
        this.idmarca = idmarca;
    }
    public Integer getIdmodelo() {
        return this.idmodelo;
    }
    
    public void setIdmodelo(Integer idmodelo) {
        this.idmodelo = idmodelo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Integer getNrocaras() {
        return this.nrocaras;
    }
    
    public void setNrocaras(Integer nrocaras) {
        this.nrocaras = nrocaras;
    }
    public String getNumeroserie() {
        return this.numeroserie;
    }
    
    public void setNumeroserie(String numeroserie) {
        this.numeroserie = numeroserie;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Integer getIdfamiliaelectronica() {
        return this.idfamiliaelectronica;
    }
    
    public void setIdfamiliaelectronica(Integer idfamiliaelectronica) {
        this.idfamiliaelectronica = idfamiliaelectronica;
    }
    public Integer getNromangueras() {
        return this.nromangueras;
    }
    
    public void setNromangueras(Integer nromangueras) {
        this.nromangueras = nromangueras;
    }
    public String getLote() {
        return this.lote;
    }
    
    public void setLote(String lote) {
        this.lote = lote;
    }
    public Set<Cara> getCaras() {
        return this.caras;
    }
    
    public void setCaras(Set<Cara> caras) {
        this.caras = caras;
    }




}


