package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA



/**
 * TurnopuntoventacajaId generated by hbm2java
 */
public class TurnopuntoventacajaId  implements java.io.Serializable {


     private int idturno;
     private int idpuntoventa;
     private int idcaja;

    public TurnopuntoventacajaId() {
    }
   
    public int getIdturno() {
        return this.idturno;
    }
    
    public void setIdturno(int idturno) {
        this.idturno = idturno;
    }
    public int getIdpuntoventa() {
        return this.idpuntoventa;
    }
    
    public void setIdpuntoventa(int idpuntoventa) {
        this.idpuntoventa = idpuntoventa;
    }
    public int getIdcaja() {
        return this.idcaja;
    }
    
    public void setIdcaja(int idcaja) {
        this.idcaja = idcaja;
    }
}


