package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Usuarioperfil generated by hbm2java
 */
public class Usuarioperfil  implements java.io.Serializable {


     private UsuarioperfilId id;
     private Perfil perfil;
     private Usuario usuario;
     private Date fecharegistro;

    public Usuarioperfil() {
    }	
   
    public UsuarioperfilId getId() {
        return this.id;
    }
    
    public void setId(UsuarioperfilId id) {
        this.id = id;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }




}


