package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Varillajeajuste generated by hbm2java
 */
public class Varillajeajuste  implements java.io.Serializable {


     private int id;
     private Varillaje varillaje;
     private Integer volumen;
     private String concepto;
     private Date fecharegistro;

    public Varillajeajuste() {
    }

	
    public Varillajeajuste(int id, Varillaje varillaje) {
        this.id = id;
        this.varillaje = varillaje;
    }
    public Varillajeajuste(int id, Varillaje varillaje, Integer volumen, String concepto, Date fecharegistro) {
       this.id = id;
       this.varillaje = varillaje;
       this.volumen = volumen;
       this.concepto = concepto;
       this.fecharegistro = fecharegistro;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Varillaje getVarillaje() {
        return this.varillaje;
    }
    
    public void setVarillaje(Varillaje varillaje) {
        this.varillaje = varillaje;
    }
    public Integer getVolumen() {
        return this.volumen;
    }
    
    public void setVolumen(Integer volumen) {
        this.volumen = volumen;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }




}


