package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Varillaje generated by hbm2java
 */
public class Varillaje  implements java.io.Serializable {


     private int id;
     private Tanque tanque;
     private Date fechalectura;
     private Integer medicionvolumen;
     private Integer medicionagua;
     private String fechanegocio;
     private Date fecharegistro;
     private Set<Varillajeajuste> varillajeajustes = new HashSet<Varillajeajuste>(0);

    public Varillaje() {
    }

	
    public Varillaje(int id, Tanque tanque) {
        this.id = id;
        this.tanque = tanque;
    }
    public Varillaje(int id, Tanque tanque, Date fechalectura, Integer medicionvolumen, Integer medicionagua, String fechanegocio, Date fecharegistro, Set<Varillajeajuste> varillajeajustes) {
       this.id = id;
       this.tanque = tanque;
       this.fechalectura = fechalectura;
       this.medicionvolumen = medicionvolumen;
       this.medicionagua = medicionagua;
       this.fechanegocio = fechanegocio;
       this.fecharegistro = fecharegistro;
       this.varillajeajustes = varillajeajustes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tanque getTanque() {
        return this.tanque;
    }
    
    public void setTanque(Tanque tanque) {
        this.tanque = tanque;
    }
    public Date getFechalectura() {
        return this.fechalectura;
    }
    
    public void setFechalectura(Date fechalectura) {
        this.fechalectura = fechalectura;
    }
    public Integer getMedicionvolumen() {
        return this.medicionvolumen;
    }
    
    public void setMedicionvolumen(Integer medicionvolumen) {
        this.medicionvolumen = medicionvolumen;
    }
    public Integer getMedicionagua() {
        return this.medicionagua;
    }
    
    public void setMedicionagua(Integer medicionagua) {
        this.medicionagua = medicionagua;
    }
    public String getFechanegocio() {
        return this.fechanegocio;
    }
    
    public void setFechanegocio(String fechanegocio) {
        this.fechanegocio = fechanegocio;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public Set<Varillajeajuste> getVarillajeajustes() {
        return this.varillajeajustes;
    }
    
    public void setVarillajeajustes(Set<Varillajeajuste> varillajeajustes) {
        this.varillajeajustes = varillajeajustes;
    }




}


