package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Caraproducto generated by hbm2java
 */
public class Caraproducto  implements java.io.Serializable {


     private CaraproductoId id;
     private Producto producto;
     private Cara cara;
     private Date fechaRegistro;
     private Set<Despacho> despachos = new HashSet<Despacho>(0);

    public Caraproducto() {
    }

	
    public Caraproducto(CaraproductoId id, Producto producto, Cara cara) {
        this.id = id;
        this.producto = producto;
        this.cara = cara;
    }
    public Caraproducto(CaraproductoId id, Producto producto, Cara cara, Date fechaRegistro, Set<Despacho> despachos) {
       this.id = id;
       this.producto = producto;
       this.cara = cara;
       this.fechaRegistro = fechaRegistro;
       this.despachos = despachos;
    }
   
    public CaraproductoId getId() {
        return this.id;
    }
    
    public void setId(CaraproductoId id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Cara getCara() {
        return this.cara;
    }
    
    public void setCara(Cara cara) {
        this.cara = cara;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<Despacho> getDespachos() {
        return this.despachos;
    }
    
    public void setDespachos(Set<Despacho> despachos) {
        this.despachos = despachos;
    }




}


