package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA



/**
 * PerfilopcionId generated by hbm2java
 */
public class PerfilopcionId  implements java.io.Serializable {


     private int idOpcion;
     private int idPerfil;

    public PerfilopcionId() {
    }

    public PerfilopcionId(int idOpcion, int idPerfil) {
       this.idOpcion = idOpcion;
       this.idPerfil = idPerfil;
    }
   
    public int getIdOpcion() {
        return this.idOpcion;
    }
    
    public void setIdOpcion(int idOpcion) {
        this.idOpcion = idOpcion;
    }
    public int getIdPerfil() {
        return this.idPerfil;
    }
    
    public void setIdPerfil(int idPerfil) {
        this.idPerfil = idPerfil;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PerfilopcionId) ) return false;
		 PerfilopcionId castOther = ( PerfilopcionId ) other; 
         
		 return (this.getIdOpcion()==castOther.getIdOpcion())
 && (this.getIdPerfil()==castOther.getIdPerfil());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdOpcion();
         result = 37 * result + this.getIdPerfil();
         return result;
   }   


}


