package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA



/**
 * PerfilopcionId generated by hbm2java
 */
public class PerfilopcionId  implements java.io.Serializable {


     private int idopcion;
     private int idperfil;

    public PerfilopcionId() {
    }

    public PerfilopcionId(int idopcion, int idperfil) {
       this.idopcion = idopcion;
       this.idperfil = idperfil;
    }
   
    public int getIdopcion() {
        return this.idopcion;
    }
    
    public void setIdopcion(int idopcion) {
        this.idopcion = idopcion;
    }
    public int getIdperfil() {
        return this.idperfil;
    }
    
    public void setIdperfil(int idperfil) {
        this.idperfil = idperfil;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PerfilopcionId) ) return false;
		 PerfilopcionId castOther = ( PerfilopcionId ) other; 
         
		 return (this.getIdopcion()==castOther.getIdopcion())
 && (this.getIdperfil()==castOther.getIdperfil());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdopcion();
         result = 37 * result + this.getIdperfil();
         return result;
   }   


}


