package pe.com.ega.sgces.model;
// Generated 17/10/2013 09:33:40 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Transacciondetalle generated by hbm2java
 */
public class Transacciondetalle  implements java.io.Serializable {


     private int id;
     private Producto producto;
     private Transaccion transaccion;
     private Long monto;
     private Integer cantidad;
     private Date fecharegistro;

    public Transacciondetalle() {
    }

	
    public Transacciondetalle(int id, Producto producto, Transaccion transaccion) {
        this.id = id;
        this.producto = producto;
        this.transaccion = transaccion;
    }
    public Transacciondetalle(int id, Producto producto, Transaccion transaccion, Long monto, Integer cantidad, Date fecharegistro) {
       this.id = id;
       this.producto = producto;
       this.transaccion = transaccion;
       this.monto = monto;
       this.cantidad = cantidad;
       this.fecharegistro = fecharegistro;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Transaccion getTransaccion() {
        return this.transaccion;
    }
    
    public void setTransaccion(Transaccion transaccion) {
        this.transaccion = transaccion;
    }
    public Long getMonto() {
        return this.monto;
    }
    
    public void setMonto(Long monto) {
        this.monto = monto;
    }
    public Integer getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Integer cantidad) {
        this.cantidad = cantidad;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }




}


