package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA



/**
 * TurnopuntoventacajaId generated by hbm2java
 */
public class TurnopuntoventacajaId  implements java.io.Serializable {


     private int idTurno;
     private int idPuntoVenta;
     private int idCaja;

    public TurnopuntoventacajaId() {
    }

    public TurnopuntoventacajaId(int idTurno, int idPuntoVenta, int idCaja) {
       this.idTurno = idTurno;
       this.idPuntoVenta = idPuntoVenta;
       this.idCaja = idCaja;
    }
   
    public int getIdTurno() {
        return this.idTurno;
    }
    
    public void setIdTurno(int idTurno) {
        this.idTurno = idTurno;
    }
    public int getIdPuntoVenta() {
        return this.idPuntoVenta;
    }
    
    public void setIdPuntoVenta(int idPuntoVenta) {
        this.idPuntoVenta = idPuntoVenta;
    }
    public int getIdCaja() {
        return this.idCaja;
    }
    
    public void setIdCaja(int idCaja) {
        this.idCaja = idCaja;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TurnopuntoventacajaId) ) return false;
		 TurnopuntoventacajaId castOther = ( TurnopuntoventacajaId ) other; 
         
		 return (this.getIdTurno()==castOther.getIdTurno())
 && (this.getIdPuntoVenta()==castOther.getIdPuntoVenta())
 && (this.getIdCaja()==castOther.getIdCaja());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTurno();
         result = 37 * result + this.getIdPuntoVenta();
         result = 37 * result + this.getIdCaja();
         return result;
   }   


}


