/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pe.com.ega.sgces.sgcespos;

import pe.com.ega.sgces.util.ImprimirComprobante;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;
import pe.com.ega.sgces.logic.ArqueoLogica;
import pe.com.ega.sgces.logic.ArqueoLogicaImpl;
import pe.com.ega.sgces.logic.CierreLogica;
import pe.com.ega.sgces.logic.CierreLogicaImpl;
import pe.com.ega.sgces.logic.DepositoLogica;
import pe.com.ega.sgces.logic.DepositoLogicaImpl;
import pe.com.ega.sgces.logic.DespachoLogica;
import pe.com.ega.sgces.logic.DespachoLogicaImpl;
import pe.com.ega.sgces.logic.MovimientoLogica;
import pe.com.ega.sgces.logic.MovimientoLogicaImpl;
import pe.com.ega.sgces.logic.TransaccionLogica;
import pe.com.ega.sgces.logic.TransaccionLogicaImpl;
import pe.com.ega.sgces.logic.TurnoLogica;
import pe.com.ega.sgces.logic.TurnoLogicaImpl;
import pe.com.ega.sgces.model.Arqueo;
import pe.com.ega.sgces.model.Despacho;


/**
 *
 * @author sistemas
 */
public class PrincipalFrame extends javax.swing.JFrame {

  private MovimientoLogica movimientoLogica;
  private DepositoLogica depositoLogica;
  private DespachoLogica despachoLogica;
  private TurnoLogica turnoLogica;
  private TransaccionLogica transaccionLogica;
  private CierreLogica cierreLogica;
  private ArrayList<Despacho> transaccions;
  private ArqueoLogica arqueoLogica;
 // private DespachoLogica despachoLogica;
  private String numero;
  
    public PrincipalFrame() {
        initComponents();
        this.setSize(554, 424);
        transaccions=new ArrayList<>();       
        
        ApplicationContext context = new ClassPathXmlApplicationContext(
				"applicationContext.xml");
		this.movimientoLogica =  context.getBean("movimientoService",
				MovimientoLogicaImpl.class);
                this.depositoLogica =  context.getBean("depositoService",
				DepositoLogicaImpl.class);
                this.despachoLogica =  context.getBean("despachoService",
				DespachoLogicaImpl.class);
                this.turnoLogica =  context.getBean("turnoService",
				TurnoLogicaImpl.class);
                this.transaccionLogica =  context.getBean("transaccionService",
				TransaccionLogicaImpl.class);
                this.cierreLogica =  context.getBean("cierreService",
				CierreLogicaImpl.class);
         pintarTabla();
         arqueoLogica =new ArqueoLogicaImpl(movimientoLogica, depositoLogica);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        panel1 = new java.awt.Panel();
        boleta = new javax.swing.JButton();
        factura = new javax.swing.JButton();
        nota = new javax.swing.JButton();
        panel3 = new java.awt.Panel();
        boleta1 = new javax.swing.JButton();
        factura1 = new javax.swing.JButton();
        nota1 = new javax.swing.JButton();
        panel2 = new java.awt.Panel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        panel4 = new java.awt.Panel();
        anular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(null);

        panel1.setBackground(new java.awt.Color(102, 255, 102));
        panel1.setLayout(null);

        boleta.setBackground(new java.awt.Color(0, 204, 0));
        boleta.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        boleta.setForeground(new java.awt.Color(255, 255, 255));
        boleta.setMnemonic(KeyEvent.VK_E);
        boleta.setText("BOLETA");
        boleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boletaActionPerformed(evt);
            }
        });
        panel1.add(boleta);
        boleta.setBounds(10, 10, 170, 100);

        factura.setBackground(new java.awt.Color(0, 204, 0));
        factura.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        factura.setForeground(new java.awt.Color(255, 255, 255));
        factura.setMnemonic(KeyEvent.VK_E);
        factura.setText("FACTURA");
        factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facturaActionPerformed(evt);
            }
        });
        panel1.add(factura);
        factura.setBounds(190, 10, 150, 100);

        nota.setBackground(new java.awt.Color(0, 204, 0));
        nota.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        nota.setForeground(new java.awt.Color(255, 255, 255));
        nota.setMnemonic(KeyEvent.VK_E);
        nota.setText("DESPACHO");
        nota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notaActionPerformed(evt);
            }
        });
        panel1.add(nota);
        nota.setBounds(350, 10, 160, 100);

        panel3.setBackground(new java.awt.Color(0, 204, 0));
        panel3.setLayout(null);

        boleta1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        boleta1.setForeground(new java.awt.Color(51, 51, 51));
        boleta1.setMnemonic(KeyEvent.VK_E);
        boleta1.setText("BOLETA");
        boleta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boleta1ActionPerformed(evt);
            }
        });
        panel3.add(boleta1);
        boleta1.setBounds(10, 10, 150, 100);

        factura1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        factura1.setForeground(new java.awt.Color(51, 51, 51));
        factura1.setMnemonic(KeyEvent.VK_E);
        factura1.setText("FACTURA");
        factura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                factura1ActionPerformed(evt);
            }
        });
        panel3.add(factura1);
        factura1.setBounds(170, 10, 150, 100);

        nota1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        nota1.setForeground(new java.awt.Color(51, 51, 51));
        nota1.setMnemonic(KeyEvent.VK_E);
        nota1.setText("FACTURA");
        nota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nota1ActionPerformed(evt);
            }
        });
        panel3.add(nota1);
        nota1.setBounds(330, 10, 150, 100);

        panel1.add(panel3);
        panel3.setBounds(10, 280, 490, 120);

        jPanel2.add(panel1);
        panel1.setBounds(10, 280, 520, 120);

        panel2.setBackground(new java.awt.Color(255, 255, 204));
        panel2.setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setMnemonic(KeyEvent.VK_A);
        jButton1.setText("ARQUEO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel2.add(jButton1);
        jButton1.setBounds(10, 10, 120, 63);

        jButton2.setBackground(new java.awt.Color(255, 255, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setMnemonic(KeyEvent.VK_T);
        jButton2.setText("TIRADA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel2.add(jButton2);
        jButton2.setBounds(10, 90, 120, 66);

        jButton3.setBackground(new java.awt.Color(255, 255, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 0, 0));
        jButton3.setMnemonic(KeyEvent.VK_C);
        jButton3.setText("CIERRE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panel2.add(jButton3);
        jButton3.setBounds(10, 250, 120, 110);

        jPanel2.add(panel2);
        panel2.setBounds(730, 30, 140, 370);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(200, 290));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(492, 190));

        tabla.setAutoCreateRowSorter(true);
        tabla.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Transaccion", "Surtidor", "Producto", "Precio", "Galones", "Monto"
            }
        ));
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabla.setMaximumSize(new java.awt.Dimension(200, 290));
        tabla.setMinimumSize(new java.awt.Dimension(200, 290));
        tabla.setPreferredSize(new java.awt.Dimension(452, 190));
        tabla.setRequestFocusEnabled(false);
        tabla.setRowHeight(36);
        tabla.setSelectionBackground(new java.awt.Color(255, 255, 0));
        tabla.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabla);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 700, 220);

        panel4.setBackground(new java.awt.Color(255, 153, 102));
        panel4.setLayout(null);

        anular.setBackground(new java.awt.Color(255, 153, 0));
        anular.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        anular.setForeground(new java.awt.Color(255, 255, 255));
        anular.setMnemonic(KeyEvent.VK_N);
        anular.setText("ANULAR");
        anular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anularActionPerformed(evt);
            }
        });
        panel4.add(anular);
        anular.setBounds(10, 10, 150, 100);

        jPanel2.add(panel4);
        panel4.setBounds(540, 280, 170, 120);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 880, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boletaActionPerformed
            OpcionFrame f=new OpcionFrame(buscar(numero), despachoLogica, movimientoLogica, turnoLogica, transaccionLogica);
            f.setSize(298,103);
            f.setTitle("Comprobante");
            f.setLocationRelativeTo(null);
            f.setVisible(true);
    }//GEN-LAST:event_boletaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Double total=0.0;
            ArrayList<Arqueo> lista=arqueoLogica.buscarPorCodigo(String.valueOf(turnoLogica.buscarPorCodigo("N").getId()));
            for (Arqueo arqueo1 : lista) {
            total=total+arqueo1.getCantidad();
            }
            ImprimirComprobante comprobante = new ImprimirComprobante();
            comprobante.imprimirArqueo("0001", String.valueOf(redondear(lista.get(1).getCantidad()))
                    , String.valueOf(redondear(lista.get(0).getCantidad())),String.valueOf(redondear(lista.get(2).getCantidad())),
                     String.valueOf(redondear(total))
                    , String.valueOf(redondear(lista.get(3).getCantidad())), "ROSARIO");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TiradaFrame f = new TiradaFrame(depositoLogica);
        f.setSize(210,233);
        f.setTitle("Tirada");
        f.setLocationRelativeTo(null);
        f.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String mensaje=cierreLogica.cierreTurno(turnoLogica.buscarPorCodigo("N"));
              if(mensaje.equalsIgnoreCase("Cierre"))
              {
                  final JPanel panel = new JPanel();
                  JOptionPane.showMessageDialog(panel,"Cierre Realizado con Existo", "Informacion", JOptionPane.OK_OPTION);
                  
              }else{

                  if(mensaje.equalsIgnoreCase("Caja no Cuadrada"))
                  {
                       final JPanel panel = new JPanel();
                       JOptionPane.showMessageDialog(panel,mensaje, "Error", JOptionPane.ERROR_MESSAGE);
                  }else{
                        final JPanel panel = new JPanel();
                        JOptionPane.showMessageDialog(panel, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
                  }
              }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void anularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anularActionPerformed
        ComprobanteFrame f = new ComprobanteFrame(turnoLogica,transaccionLogica);
        f.setSize(528,202);
        f.setTitle("Anular Comprobantes");
        f.setLocationRelativeTo(null);
        f.setVisible(true);
        f.setSize(520,217);
    }//GEN-LAST:event_anularActionPerformed

    private void facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facturaActionPerformed
          FacturaFrame f=new FacturaFrame(buscar(numero),despachoLogica, movimientoLogica, turnoLogica, transaccionLogica);
            f.setSize(391,166);
            f.setTitle("Factura");
            f.setLocationRelativeTo(null);
            f.setVisible(true);
    }//GEN-LAST:event_facturaActionPerformed

    private void notaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notaActionPerformed
         NotaFrame f=new NotaFrame(buscar(numero));
            f.setSize(391,290);
            f.setTitle("Nota Despacho");
            f.setLocationRelativeTo(null);
            f.setVisible(true);
    }//GEN-LAST:event_notaActionPerformed

    private void boleta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boleta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boleta1ActionPerformed

    private void factura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_factura1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_factura1ActionPerformed

    private void nota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nota1ActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PrincipalFrame().setVisible(true);
               
                 try {
            UIManager.setLookAndFeel("com.seaglasslookandfeel.SeaGlassLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
        }
            }
        }
);
    }
    
  private void pintarTabla(){
  System.out.println("se llamo a pintar tabla");
  String[] titulo=new String[]{"Codigo","Fecha","Producto","Precio","Galones","Monto"};

  try {
  transaccions=(ArrayList<Despacho>) despachoLogica.buscarTodos();
  } catch (Exception ex) {
//TODO Agregar log de errores.
  }

  Object[][] arre=new Object[transaccions.size()][7];
  int i=0;
  for(Despacho t:transaccions){
      arre[i][0]=t.getId();
      arre[i][1]=t.getFecharegistro();
      arre[i][2]=t.getProducto().getNombre();
      arre[i][3]=t.getPreciounitario();
      arre[i][4]=t.getNrogalones();
      arre[i][5]=t.getMontosoles();
      i++;
  }

  tabla.addMouseListener(new SelectListener());
  DefaultTableModel modelo=new DefaultTableModel(arre, titulo);
  tabla.setModel(modelo);
  int anchos[] = {50, 100, 200, 50, 50, 50};
  tabla.getColumnModel().getColumn(0).setMaxWidth(0);
  tabla.getColumnModel().getColumn(0).setMinWidth(0);
  tabla.getColumnModel().getColumn(0).setPreferredWidth(0);
  tabla.getColumnModel().getColumn(1).setMaxWidth(0);
  tabla.getColumnModel().getColumn(1).setMinWidth(0);
  tabla.getColumnModel().getColumn(1).setPreferredWidth(0);
  for (int x = 2; x < tabla.getColumnCount(); x++) {
    tabla.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
    tabla.getColumnModel().getColumn(x).setResizable(false);
  }
  jScrollPane1.setViewportView(tabla); 
}
     
  class SelectListener extends MouseAdapter {

        @Override
        public void mouseClicked(MouseEvent e) {
           // select(e);
        }

        @Override
        public void mousePressed(MouseEvent e) {
            select(e);
        }

       
        private void select(MouseEvent e){
            int row=tabla.getSelectedRow();
            String txt[] = new String[tabla.getColumnCount()];
            for (int i = 0; i < tabla.getColumnCount(); i++) {
                txt[i]=String.valueOf(tabla.getValueAt(row, 0));           
            }
            numero=txt[0];
            System.out.println("Numero"+numero);          
        }      
  }
     
  private Despacho buscar(String codigo){
      int cod= Integer.parseInt(codigo);
      Despacho desp=null;
      for(Despacho t:transaccions){
            if(cod==t.getId()){
                desp=t;
                break;
            }
  }
        return desp;
  }
     
  private void salir (MouseEvent evt){
       actionPerformed(evt);
   }

  private void actionPerformed(MouseEvent evt) {
        setVisible(false);
        dispose();
   }
  
  
    public static double redondear(double numero) 
       {        
           return Math.rint(numero*100)/100; 
       }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anular;
    private javax.swing.JButton boleta;
    private javax.swing.JButton boleta1;
    private javax.swing.JButton factura;
    private javax.swing.JButton factura1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nota;
    private javax.swing.JButton nota1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
