package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cara generated by hbm2java
 */
public class Cara  implements java.io.Serializable {


     private int id;
     private Surtidor surtidor;
     private Date fechaRegistro;
     private String codigo;
     private Set<Caraproducto> caraproductos = new HashSet<Caraproducto>(0);

    public Cara() {
    }

	
    public Cara(int id, Surtidor surtidor) {
        this.id = id;
        this.surtidor = surtidor;
    }
    public Cara(int id, Surtidor surtidor, Date fechaRegistro, String codigo, Set<Caraproducto> caraproductos) {
       this.id = id;
       this.surtidor = surtidor;
       this.fechaRegistro = fechaRegistro;
       this.codigo = codigo;
       this.caraproductos = caraproductos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Surtidor getSurtidor() {
        return this.surtidor;
    }
    
    public void setSurtidor(Surtidor surtidor) {
        this.surtidor = surtidor;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set<Caraproducto> getCaraproductos() {
        return this.caraproductos;
    }
    
    public void setCaraproductos(Set<Caraproducto> caraproductos) {
        this.caraproductos = caraproductos;
    }




}


