package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int id;
     private String numeroDocumento;
     private String razonSocial;
     private Integer idTipoDocumento;
     private Date fechaRegistro;
     private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);
     private Set<Tarjeta> tarjetas = new HashSet<Tarjeta>(0);
     private Set<Cuenta> cuentas = new HashSet<Cuenta>(0);

    public Cliente() {
    }

	
    public Cliente(int id) {
        this.id = id;
    }
    public Cliente(int id, String numeroDocumento, String razonSocial, Integer idTipoDocumento, Date fechaRegistro, Set<Transaccion> transaccions, Set<Tarjeta> tarjetas, Set<Cuenta> cuentas) {
       this.id = id;
       this.numeroDocumento = numeroDocumento;
       this.razonSocial = razonSocial;
       this.idTipoDocumento = idTipoDocumento;
       this.fechaRegistro = fechaRegistro;
       this.transaccions = transaccions;
       this.tarjetas = tarjetas;
       this.cuentas = cuentas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public Integer getIdTipoDocumento() {
        return this.idTipoDocumento;
    }
    
    public void setIdTipoDocumento(Integer idTipoDocumento) {
        this.idTipoDocumento = idTipoDocumento;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<Transaccion> getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set<Transaccion> transaccions) {
        this.transaccions = transaccions;
    }
    public Set<Tarjeta> getTarjetas() {
        return this.tarjetas;
    }
    
    public void setTarjetas(Set<Tarjeta> tarjetas) {
        this.tarjetas = tarjetas;
    }
    public Set<Cuenta> getCuentas() {
        return this.cuentas;
    }
    
    public void setCuentas(Set<Cuenta> cuentas) {
        this.cuentas = cuentas;
    }




}


