package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Despacho generated by hbm2java
 */
public class Despacho  implements java.io.Serializable {


     private int id;
     private Producto producto;
     private Caraproducto caraproducto;
     private Integer idEstado;
     private Long montoSoles;
     private Long nroGalones;
     private Long precioUnitario;
     private Date fechaRegistro;
     private Set<Transaccion> transaccions = new HashSet<Transaccion>(0);

    public Despacho() {
    }

	
    public Despacho(int id, Producto producto, Caraproducto caraproducto) {
        this.id = id;
        this.producto = producto;
        this.caraproducto = caraproducto;
    }
    public Despacho(int id, Producto producto, Caraproducto caraproducto, Integer idEstado, Long montoSoles, Long nroGalones, Long precioUnitario, Date fechaRegistro, Set<Transaccion> transaccions) {
       this.id = id;
       this.producto = producto;
       this.caraproducto = caraproducto;
       this.idEstado = idEstado;
       this.montoSoles = montoSoles;
       this.nroGalones = nroGalones;
       this.precioUnitario = precioUnitario;
       this.fechaRegistro = fechaRegistro;
       this.transaccions = transaccions;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Caraproducto getCaraproducto() {
        return this.caraproducto;
    }
    
    public void setCaraproducto(Caraproducto caraproducto) {
        this.caraproducto = caraproducto;
    }
    public Integer getIdEstado() {
        return this.idEstado;
    }
    
    public void setIdEstado(Integer idEstado) {
        this.idEstado = idEstado;
    }
    public Long getMontoSoles() {
        return this.montoSoles;
    }
    
    public void setMontoSoles(Long montoSoles) {
        this.montoSoles = montoSoles;
    }
    public Long getNroGalones() {
        return this.nroGalones;
    }
    
    public void setNroGalones(Long nroGalones) {
        this.nroGalones = nroGalones;
    }
    public Long getPrecioUnitario() {
        return this.precioUnitario;
    }
    
    public void setPrecioUnitario(Long precioUnitario) {
        this.precioUnitario = precioUnitario;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<Transaccion> getTransaccions() {
        return this.transaccions;
    }
    
    public void setTransaccions(Set<Transaccion> transaccions) {
        this.transaccions = transaccions;
    }




}


