package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA



/**
 * DistritoId generated by hbm2java
 */
public class DistritoId  implements java.io.Serializable {


     private String id;
     private String idProvincia;
     private String idDepartamento;

    public DistritoId() {
    }

    public DistritoId(String id, String idProvincia, String idDepartamento) {
       this.id = id;
       this.idProvincia = idProvincia;
       this.idDepartamento = idDepartamento;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getIdProvincia() {
        return this.idProvincia;
    }
    
    public void setIdProvincia(String idProvincia) {
        this.idProvincia = idProvincia;
    }
    public String getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(String idDepartamento) {
        this.idDepartamento = idDepartamento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof DistritoId) ) return false;
		 DistritoId castOther = ( DistritoId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getIdProvincia()==castOther.getIdProvincia()) || ( this.getIdProvincia()!=null && castOther.getIdProvincia()!=null && this.getIdProvincia().equals(castOther.getIdProvincia()) ) )
 && ( (this.getIdDepartamento()==castOther.getIdDepartamento()) || ( this.getIdDepartamento()!=null && castOther.getIdDepartamento()!=null && this.getIdDepartamento().equals(castOther.getIdDepartamento()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getIdProvincia() == null ? 0 : this.getIdProvincia().hashCode() );
         result = 37 * result + ( getIdDepartamento() == null ? 0 : this.getIdDepartamento().hashCode() );
         return result;
   }   


}


