package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Impresorapuntoventa generated by hbm2java
 */
public class Impresorapuntoventa  implements java.io.Serializable {


     private ImpresorapuntoventaId id;
     private Impresora impresora;
     private Puntoventa puntoventa;
     private Date fechaRegistro;

    public Impresorapuntoventa() {
    }

	
    public Impresorapuntoventa(ImpresorapuntoventaId id, Impresora impresora, Puntoventa puntoventa) {
        this.id = id;
        this.impresora = impresora;
        this.puntoventa = puntoventa;
    }
    public Impresorapuntoventa(ImpresorapuntoventaId id, Impresora impresora, Puntoventa puntoventa, Date fechaRegistro) {
       this.id = id;
       this.impresora = impresora;
       this.puntoventa = puntoventa;
       this.fechaRegistro = fechaRegistro;
    }
   
    public ImpresorapuntoventaId getId() {
        return this.id;
    }
    
    public void setId(ImpresorapuntoventaId id) {
        this.id = id;
    }
    public Impresora getImpresora() {
        return this.impresora;
    }
    
    public void setImpresora(Impresora impresora) {
        this.impresora = impresora;
    }
    public Puntoventa getPuntoventa() {
        return this.puntoventa;
    }
    
    public void setPuntoventa(Puntoventa puntoventa) {
        this.puntoventa = puntoventa;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


