package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Movimiento generated by hbm2java
 */
public class Movimiento  implements java.io.Serializable {


     private int id;
     private Turnopuntoventacaja turnopuntoventacaja;
     private Transaccion transaccion;
     private Integer idTipoPago;
     private Long montoRecibido;
     private Long montoTotal;
     private Long montoDevuelto;
     private Date fechaRegistro;
     private String nroOperacion;

    public Movimiento() {
    }

	
    public Movimiento(int id, Turnopuntoventacaja turnopuntoventacaja, Transaccion transaccion) {
        this.id = id;
        this.turnopuntoventacaja = turnopuntoventacaja;
        this.transaccion = transaccion;
    }
    public Movimiento(int id, Turnopuntoventacaja turnopuntoventacaja, Transaccion transaccion, Integer idTipoPago, Long montoRecibido, Long montoTotal, Long montoDevuelto, Date fechaRegistro, String nroOperacion) {
       this.id = id;
       this.turnopuntoventacaja = turnopuntoventacaja;
       this.transaccion = transaccion;
       this.idTipoPago = idTipoPago;
       this.montoRecibido = montoRecibido;
       this.montoTotal = montoTotal;
       this.montoDevuelto = montoDevuelto;
       this.fechaRegistro = fechaRegistro;
       this.nroOperacion = nroOperacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Turnopuntoventacaja getTurnopuntoventacaja() {
        return this.turnopuntoventacaja;
    }
    
    public void setTurnopuntoventacaja(Turnopuntoventacaja turnopuntoventacaja) {
        this.turnopuntoventacaja = turnopuntoventacaja;
    }
    public Transaccion getTransaccion() {
        return this.transaccion;
    }
    
    public void setTransaccion(Transaccion transaccion) {
        this.transaccion = transaccion;
    }
    public Integer getIdTipoPago() {
        return this.idTipoPago;
    }
    
    public void setIdTipoPago(Integer idTipoPago) {
        this.idTipoPago = idTipoPago;
    }
    public Long getMontoRecibido() {
        return this.montoRecibido;
    }
    
    public void setMontoRecibido(Long montoRecibido) {
        this.montoRecibido = montoRecibido;
    }
    public Long getMontoTotal() {
        return this.montoTotal;
    }
    
    public void setMontoTotal(Long montoTotal) {
        this.montoTotal = montoTotal;
    }
    public Long getMontoDevuelto() {
        return this.montoDevuelto;
    }
    
    public void setMontoDevuelto(Long montoDevuelto) {
        this.montoDevuelto = montoDevuelto;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public String getNroOperacion() {
        return this.nroOperacion;
    }
    
    public void setNroOperacion(String nroOperacion) {
        this.nroOperacion = nroOperacion;
    }




}


