package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Provincia generated by hbm2java
 */
public class Provincia  implements java.io.Serializable {


     private ProvinciaId id;
     private Departamento departamento;
     private String nombre;
     private Set<Distrito> distritos = new HashSet<Distrito>(0);

    public Provincia() {
    }

	
    public Provincia(ProvinciaId id, Departamento departamento) {
        this.id = id;
        this.departamento = departamento;
    }
    public Provincia(ProvinciaId id, Departamento departamento, String nombre, Set<Distrito> distritos) {
       this.id = id;
       this.departamento = departamento;
       this.nombre = nombre;
       this.distritos = distritos;
    }
   
    public ProvinciaId getId() {
        return this.id;
    }
    
    public void setId(ProvinciaId id) {
        this.id = id;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set<Distrito> getDistritos() {
        return this.distritos;
    }
    
    public void setDistritos(Set<Distrito> distritos) {
        this.distritos = distritos;
    }




}


