package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA



/**
 * PuntoacumuladoId generated by hbm2java
 */
public class PuntoacumuladoId  implements java.io.Serializable {


     private int idTransaccion;
     private int idTarjeta;

    public PuntoacumuladoId() {
    }

    public PuntoacumuladoId(int idTransaccion, int idTarjeta) {
       this.idTransaccion = idTransaccion;
       this.idTarjeta = idTarjeta;
    }
   
    public int getIdTransaccion() {
        return this.idTransaccion;
    }
    
    public void setIdTransaccion(int idTransaccion) {
        this.idTransaccion = idTransaccion;
    }
    public int getIdTarjeta() {
        return this.idTarjeta;
    }
    
    public void setIdTarjeta(int idTarjeta) {
        this.idTarjeta = idTarjeta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PuntoacumuladoId) ) return false;
		 PuntoacumuladoId castOther = ( PuntoacumuladoId ) other; 
         
		 return (this.getIdTransaccion()==castOther.getIdTransaccion())
 && (this.getIdTarjeta()==castOther.getIdTarjeta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTransaccion();
         result = 37 * result + this.getIdTarjeta();
         return result;
   }   


}


