package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Subcuenta generated by hbm2java
 */
public class Subcuenta  implements java.io.Serializable {


     private int id;
     private Cuenta cuenta;
     private Producto producto;
     private Tarjeta tarjeta;
     private String descriocion;
     private Integer idTipoMoneda;
     private Integer saldo;
     private Integer limiteCredito;
     private Date fechaRegistro;

    public Subcuenta() {
    }

	
    public Subcuenta(int id, Cuenta cuenta, Producto producto, Tarjeta tarjeta) {
        this.id = id;
        this.cuenta = cuenta;
        this.producto = producto;
        this.tarjeta = tarjeta;
    }
    public Subcuenta(int id, Cuenta cuenta, Producto producto, Tarjeta tarjeta, String descriocion, Integer idTipoMoneda, Integer saldo, Integer limiteCredito, Date fechaRegistro) {
       this.id = id;
       this.cuenta = cuenta;
       this.producto = producto;
       this.tarjeta = tarjeta;
       this.descriocion = descriocion;
       this.idTipoMoneda = idTipoMoneda;
       this.saldo = saldo;
       this.limiteCredito = limiteCredito;
       this.fechaRegistro = fechaRegistro;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cuenta getCuenta() {
        return this.cuenta;
    }
    
    public void setCuenta(Cuenta cuenta) {
        this.cuenta = cuenta;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Tarjeta getTarjeta() {
        return this.tarjeta;
    }
    
    public void setTarjeta(Tarjeta tarjeta) {
        this.tarjeta = tarjeta;
    }
    public String getDescriocion() {
        return this.descriocion;
    }
    
    public void setDescriocion(String descriocion) {
        this.descriocion = descriocion;
    }
    public Integer getIdTipoMoneda() {
        return this.idTipoMoneda;
    }
    
    public void setIdTipoMoneda(Integer idTipoMoneda) {
        this.idTipoMoneda = idTipoMoneda;
    }
    public Integer getSaldo() {
        return this.saldo;
    }
    
    public void setSaldo(Integer saldo) {
        this.saldo = saldo;
    }
    public Integer getLimiteCredito() {
        return this.limiteCredito;
    }
    
    public void setLimiteCredito(Integer limiteCredito) {
        this.limiteCredito = limiteCredito;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


