package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tanque generated by hbm2java
 */
public class Tanque  implements java.io.Serializable {


     private int id;
     private Producto producto;
     private Estacionservicio estacionservicio;
     private Date fechaRegistro;
     private Integer capacidad;
     private Integer numero;
     private Integer alturaVarillaje;
     private Integer alturaSensor;
     private Set<Varillaje> varillajes = new HashSet<Varillaje>(0);

    public Tanque() {
    }

	
    public Tanque(int id, Producto producto, Estacionservicio estacionservicio) {
        this.id = id;
        this.producto = producto;
        this.estacionservicio = estacionservicio;
    }
    public Tanque(int id, Producto producto, Estacionservicio estacionservicio, Date fechaRegistro, Integer capacidad, Integer numero, Integer alturaVarillaje, Integer alturaSensor, Set<Varillaje> varillajes) {
       this.id = id;
       this.producto = producto;
       this.estacionservicio = estacionservicio;
       this.fechaRegistro = fechaRegistro;
       this.capacidad = capacidad;
       this.numero = numero;
       this.alturaVarillaje = alturaVarillaje;
       this.alturaSensor = alturaSensor;
       this.varillajes = varillajes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Estacionservicio getEstacionservicio() {
        return this.estacionservicio;
    }
    
    public void setEstacionservicio(Estacionservicio estacionservicio) {
        this.estacionservicio = estacionservicio;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Integer getCapacidad() {
        return this.capacidad;
    }
    
    public void setCapacidad(Integer capacidad) {
        this.capacidad = capacidad;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Integer getAlturaVarillaje() {
        return this.alturaVarillaje;
    }
    
    public void setAlturaVarillaje(Integer alturaVarillaje) {
        this.alturaVarillaje = alturaVarillaje;
    }
    public Integer getAlturaSensor() {
        return this.alturaSensor;
    }
    
    public void setAlturaSensor(Integer alturaSensor) {
        this.alturaSensor = alturaSensor;
    }
    public Set<Varillaje> getVarillajes() {
        return this.varillajes;
    }
    
    public void setVarillajes(Set<Varillaje> varillajes) {
        this.varillajes = varillajes;
    }




}


