package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Trabajador generated by hbm2java
 */
public class Trabajador  implements java.io.Serializable {


     private int id;
     private Estacionservicio estacionservicio;
     private String nombre;
     private String apellidoPaterno;
     private String apellidoMaterno;
     private String dni;
     private String correo;
     private String telefono;
     private Integer idCargo;
     private Integer idEstadoCivil;
     private Date fechaNacimiento;
     private Date fechaRegistro;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);
     private Set<Caja> cajas = new HashSet<Caja>(0);

    public Trabajador() {
    }

	
    public Trabajador(int id, Estacionservicio estacionservicio) {
        this.id = id;
        this.estacionservicio = estacionservicio;
    }
    public Trabajador(int id, Estacionservicio estacionservicio, String nombre, String apellidoPaterno, String apellidoMaterno, String dni, String correo, String telefono, Integer idCargo, Integer idEstadoCivil, Date fechaNacimiento, Date fechaRegistro, Set<Usuario> usuarios, Set<Caja> cajas) {
       this.id = id;
       this.estacionservicio = estacionservicio;
       this.nombre = nombre;
       this.apellidoPaterno = apellidoPaterno;
       this.apellidoMaterno = apellidoMaterno;
       this.dni = dni;
       this.correo = correo;
       this.telefono = telefono;
       this.idCargo = idCargo;
       this.idEstadoCivil = idEstadoCivil;
       this.fechaNacimiento = fechaNacimiento;
       this.fechaRegistro = fechaRegistro;
       this.usuarios = usuarios;
       this.cajas = cajas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Estacionservicio getEstacionservicio() {
        return this.estacionservicio;
    }
    
    public void setEstacionservicio(Estacionservicio estacionservicio) {
        this.estacionservicio = estacionservicio;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidoPaterno() {
        return this.apellidoPaterno;
    }
    
    public void setApellidoPaterno(String apellidoPaterno) {
        this.apellidoPaterno = apellidoPaterno;
    }
    public String getApellidoMaterno() {
        return this.apellidoMaterno;
    }
    
    public void setApellidoMaterno(String apellidoMaterno) {
        this.apellidoMaterno = apellidoMaterno;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Integer getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(Integer idCargo) {
        this.idCargo = idCargo;
    }
    public Integer getIdEstadoCivil() {
        return this.idEstadoCivil;
    }
    
    public void setIdEstadoCivil(Integer idEstadoCivil) {
        this.idEstadoCivil = idEstadoCivil;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    public Set<Caja> getCajas() {
        return this.cajas;
    }
    
    public void setCajas(Set<Caja> cajas) {
        this.cajas = cajas;
    }




}


