package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Usuarioperfil generated by hbm2java
 */
public class Usuarioperfil  implements java.io.Serializable {


     private UsuarioperfilId id;
     private Perfil perfil;
     private Usuario usuario;
     private Date fechaRegistro;

    public Usuarioperfil() {
    }

	
    public Usuarioperfil(UsuarioperfilId id, Perfil perfil, Usuario usuario) {
        this.id = id;
        this.perfil = perfil;
        this.usuario = usuario;
    }
    public Usuarioperfil(UsuarioperfilId id, Perfil perfil, Usuario usuario, Date fechaRegistro) {
       this.id = id;
       this.perfil = perfil;
       this.usuario = usuario;
       this.fechaRegistro = fechaRegistro;
    }
   
    public UsuarioperfilId getId() {
        return this.id;
    }
    
    public void setId(UsuarioperfilId id) {
        this.id = id;
    }
    public Perfil getPerfil() {
        return this.perfil;
    }
    
    public void setPerfil(Perfil perfil) {
        this.perfil = perfil;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }




}


