package pe.com.ega.sgces.model;
// Generated 04/06/2013 01:38:23 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Varillaje generated by hbm2java
 */
public class Varillaje  implements java.io.Serializable {


     private int id;
     private Tanque tanque;
     private Date fechaLectura;
     private Integer medicionVolumen;
     private Integer medicionAgua;
     private String fechaNegocio;
     private Date fechaRegistro;
     private Set<Varillajeajuste> varillajeajustes = new HashSet<Varillajeajuste>(0);

    public Varillaje() {
    }

	
    public Varillaje(int id, Tanque tanque) {
        this.id = id;
        this.tanque = tanque;
    }
    public Varillaje(int id, Tanque tanque, Date fechaLectura, Integer medicionVolumen, Integer medicionAgua, String fechaNegocio, Date fechaRegistro, Set<Varillajeajuste> varillajeajustes) {
       this.id = id;
       this.tanque = tanque;
       this.fechaLectura = fechaLectura;
       this.medicionVolumen = medicionVolumen;
       this.medicionAgua = medicionAgua;
       this.fechaNegocio = fechaNegocio;
       this.fechaRegistro = fechaRegistro;
       this.varillajeajustes = varillajeajustes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Tanque getTanque() {
        return this.tanque;
    }
    
    public void setTanque(Tanque tanque) {
        this.tanque = tanque;
    }
    public Date getFechaLectura() {
        return this.fechaLectura;
    }
    
    public void setFechaLectura(Date fechaLectura) {
        this.fechaLectura = fechaLectura;
    }
    public Integer getMedicionVolumen() {
        return this.medicionVolumen;
    }
    
    public void setMedicionVolumen(Integer medicionVolumen) {
        this.medicionVolumen = medicionVolumen;
    }
    public Integer getMedicionAgua() {
        return this.medicionAgua;
    }
    
    public void setMedicionAgua(Integer medicionAgua) {
        this.medicionAgua = medicionAgua;
    }
    public String getFechaNegocio() {
        return this.fechaNegocio;
    }
    
    public void setFechaNegocio(String fechaNegocio) {
        this.fechaNegocio = fechaNegocio;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set<Varillajeajuste> getVarillajeajustes() {
        return this.varillajeajustes;
    }
    
    public void setVarillajeajustes(Set<Varillajeajuste> varillajeajustes) {
        this.varillajeajustes = varillajeajustes;
    }




}


